package com.wms.service;
import com.wms.common.BusinessException; import com.wms.dto.*; import com.wms.model.entity.*; import com.wms.repository.*; import org.springframework.security.access.AccessDeniedException; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.BigDecimal; import java.util.*;
@Service public class AdjustmentService {
 private final AdjustmentOrderRepository adjustments; private final ItemRepository items; private final WarehouseRepository warehouses; private final InventoryRepository inventories; private final InventoryService inventory; private final DocumentNumberService numbers;
 public AdjustmentService(AdjustmentOrderRepository adjustments,ItemRepository items,WarehouseRepository warehouses,InventoryRepository inventories,InventoryService inventory,DocumentNumberService numbers){this.adjustments=adjustments;this.items=items;this.warehouses=warehouses;this.inventories=inventories;this.inventory=inventory;this.numbers=numbers;}
 @Transactional public Map<String,Object> create(AdjustmentRequest r){AdjustmentOrder a=new AdjustmentOrder();a.setAdjustmentNo(numbers.next("LOSS".equals(r.action())?"BSS":"BSY"));a.setAction(r.action());a.setWarehouse(warehouse(r.warehouseId()));a.setReason(r.reason());a.setRemark(r.remark());a.replaceLines(r.lines().stream().map(x->{AdjustmentLine l=new AdjustmentLine();l.setItem(item(x.itemCode()));l.setLocationCode(x.locationCode());l.setBatchNo(normalizeBatch(x.batchNo()));l.setQuantity(x.quantity());return l;}).toList());return view(adjustments.save(a));}
 @Transactional public Map<String,Object> review(Long id,ReviewRequest r){AdjustmentOrder a=adjustment(id);ensureAdmin();if(!"DRAFT".equals(a.getStatus()))throw new BusinessException("只有草稿报损报溢单可审核");if(!Set.of("APPROVE","REJECT").contains(r.action()))throw new BusinessException("审核动作必须为 APPROVE 或 REJECT");a.setStatus("APPROVE".equals(r.action())?"APPROVED":"REJECTED");a.setReviewer(username());return view(a);}
 @Transactional public Map<String,Object> complete(Long id){AdjustmentOrder a=adjustment(id);if(!"APPROVED".equals(a.getStatus()))throw new BusinessException("只有已审核报损报溢单可执行");for(AdjustmentLine l:a.getLines()){if("LOSS".equals(a.getAction()))inventory.adjust(a.getAdjustmentNo(),l.getItem().getCode(),a.getWarehouse().getId(),l.getLocationCode(),l.getBatchNo(),inventoryCurrent(a,l).subtract(l.getQuantity()),a.getReason());else inventory.adjust(a.getAdjustmentNo(),l.getItem().getCode(),a.getWarehouse().getId(),l.getLocationCode(),l.getBatchNo(),inventoryCurrent(a,l).add(l.getQuantity()),a.getReason());}a.setStatus("COMPLETED");return view(a);}
 public List<Map<String,Object>> list(){return adjustments.findAllDetailed().stream().map(this::view).toList();}
 private BigDecimal inventoryCurrent(AdjustmentOrder a,AdjustmentLine l){Inventory inv=inventories.findAllDetailed().stream().filter(x->x.getItem().getId().equals(l.getItem().getId())&&x.getWarehouse().getId().equals(a.getWarehouse().getId())&&Objects.equals(x.getLocation()==null?null:x.getLocation().getCode(),l.getLocationCode())&&Objects.equals(normalizeBatch(x.getBatchNo()),normalizeBatch(l.getBatchNo()))).findFirst().orElse(null);return inv==null?BigDecimal.ZERO:inv.getQuantity();}
 private String normalizeBatch(String b){return b==null||b.isBlank()?null:b.trim();}
 private AdjustmentOrder adjustment(Long id){return adjustments.findDetailedById(id).orElseThrow(()->new BusinessException("报损报溢单不存在"));}private Item item(String code){return items.findByCode(code).orElseThrow(()->new BusinessException("物品不存在："+code));}private Warehouse warehouse(Long id){return warehouses.findById(id).orElseThrow(()->new BusinessException("仓库不存在"));}
 private String username(){Object p=SecurityContextHolder.getContext().getAuthentication().getPrincipal();return p instanceof com.wms.security.TokenService.Principal x?x.username():"system";}private void ensureAdmin(){Object p=SecurityContextHolder.getContext().getAuthentication().getPrincipal();if(!(p instanceof com.wms.security.TokenService.Principal x)||!"ADMIN".equals(x.role()))throw new AccessDeniedException("仅管理员可执行审核操作");}
 private Map<String,Object> view(AdjustmentOrder a){Map<String,Object> m=new LinkedHashMap<>();m.put("id",a.getId());m.put("adjustmentNo",a.getAdjustmentNo());m.put("action",a.getAction());m.put("status",a.getStatus());m.put("warehouseId",a.getWarehouse().getId());m.put("warehouseName",a.getWarehouse().getName());m.put("reason",a.getReason());m.put("remark",a.getRemark());m.put("reviewer",a.getReviewer());m.put("createdAt",a.getCreatedAt());m.put("lines",a.getLines().stream().map(l->Map.of("id",l.getId(),"itemCode",l.getItem().getCode(),"itemName",l.getItem().getName(),"locationCode",l.getLocationCode(),"batchNo",l.getBatchNo()==null?"":l.getBatchNo(),"quantity",l.getQuantity())).toList());return m;}
}