package com.wms.service;
import com.wms.common.BusinessException; import com.wms.dto.*; import com.wms.model.entity.*; import com.wms.repository.*; import org.slf4j.Logger; import org.slf4j.LoggerFactory; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.security.access.AccessDeniedException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.BigDecimal; import java.util.*;

@Service public class DocumentService {
 private static final Logger log = LoggerFactory.getLogger(DocumentService.class);
 private final StockDocumentRepository docs; private final TransferOrderRepository transfers; private final StocktakeOrderRepository stocktakes; private final ItemRepository items; private final WarehouseRepository warehouses; private final BusinessPartnerRepository partners; private final InventoryRepository inventories; private final InventoryService inventory; private final DocumentNumberService numbers;
 public DocumentService(StockDocumentRepository docs,TransferOrderRepository transfers,StocktakeOrderRepository stocktakes,ItemRepository items,WarehouseRepository warehouses,BusinessPartnerRepository partners,InventoryRepository inventories,InventoryService inventory,DocumentNumberService numbers){this.docs=docs;this.transfers=transfers;this.stocktakes=stocktakes;this.items=items;this.warehouses=warehouses;this.partners=partners;this.inventories=inventories;this.inventory=inventory;this.numbers=numbers;}
 @Transactional public Map<String,Object> createDocument(DocumentRequest r){StockDocument d=new StockDocument();d.setDocumentNo(numbers.next(r.type().equals("IN")?"RKD":"CKD"));d.setType(r.type());d.setWarehouse(warehouse(r.warehouseId()));d.setPartner(r.partnerId()==null?null:partner(r.type(),r.partnerId()));d.setBusinessDate(r.businessDate()==null?java.time.LocalDate.now():r.businessDate());d.setRemark(r.remark());d.replaceLines(r.lines().stream().map(x->{StockDocumentLine l=new StockDocumentLine();l.setItem(item(x.itemCode()));l.setLocationCode(x.locationCode());l.setQuantity(x.quantity());l.setUnitPrice(x.unitPrice());l.setBatchNo(x.batchNo());l.setRemark(x.remark());return l;}).toList());log.info("单据创建: docNo={}, type={}, warehouseId={}", d.getDocumentNo(), r.type(), r.warehouseId());return documentView(docs.save(d));}
 @Transactional public Map<String,Object> reviewDocument(Long id,ReviewRequest r){StockDocument d=document(id);ensureAdmin();if(!"DRAFT".equals(d.getStatus()))throw new BusinessException("只有草稿单可审核");if(!Set.of("APPROVE","REJECT").contains(r.action()))throw new BusinessException("审核动作必须为 APPROVE 或 REJECT");d.setStatus("APPROVE".equals(r.action())?"APPROVED":"REJECTED");d.setReviewer(username());d.setReviewRemark(r.remark());log.info("单据审核: docNo={}, action={}, reviewer={}", d.getDocumentNo(), r.action(), username());return documentView(d);}
 @Transactional public Map<String,Object> completeDocument(Long id){StockDocument d=document(id);if(!"APPROVED".equals(d.getStatus()))throw new BusinessException("只有已审核单据可执行");for(StockDocumentLine l:d.getLines()){if("IN".equals(d.getType()))inventory.stockIn(new StockInRequest(l.getItem().getCode(),l.getQuantity(),l.getUnitPrice(),d.getWarehouse().getId(),l.getLocationCode(),l.getBatchNo(),lineRemark(d,l)),d.getDocumentNo(),TransactionType.IN);else inventory.stockOut(new StockOutRequest(l.getItem().getCode(),l.getQuantity(),l.getUnitPrice(),d.getWarehouse().getId(),l.getLocationCode(),l.getBatchNo(),lineRemark(d,l)),d.getDocumentNo(),TransactionType.OUT);}d.setStatus("COMPLETED");log.info("单据执行: docNo={}, type={}", d.getDocumentNo(), d.getType());return documentView(d);}
 @Transactional public Map<String,Object> cancelDocument(Long id){StockDocument d=document(id);if("COMPLETED".equals(d.getStatus()))throw new BusinessException("已执行单据不可取消");d.setStatus("CANCELLED");return documentView(d);}
 @Transactional public Map<String,Object> createTransfer(TransferRequest r){if(r.sourceWarehouseId().equals(r.targetWarehouseId()))throw new BusinessException("调出与调入仓库不能相同");TransferOrder t=new TransferOrder();t.setTransferNo(numbers.next("DBD"));t.setSourceWarehouse(warehouse(r.sourceWarehouseId()));t.setTargetWarehouse(warehouse(r.targetWarehouseId()));t.setRemark(r.remark());t.replaceLines(r.lines().stream().map(x->{TransferLine l=new TransferLine();l.setItem(item(x.itemCode()));l.setSourceLocationCode(x.sourceLocationCode());l.setTargetLocationCode(x.targetLocationCode());l.setBatchNo(normalizeBatch(x.batchNo()));l.setQuantity(x.quantity());return l;}).toList());return transferView(transfers.save(t));}
 @Transactional public Map<String,Object> reviewTransfer(Long id,ReviewRequest r){TransferOrder t=transfer(id);ensureAdmin();if(!"DRAFT".equals(t.getStatus()))throw new BusinessException("只有草稿调拨单可审核");if(!Set.of("APPROVE","REJECT").contains(r.action()))throw new BusinessException("审核动作必须为 APPROVE 或 REJECT");t.setStatus("APPROVE".equals(r.action())?"APPROVED":"REJECTED");t.setReviewer(username());return transferView(t);}
 @Transactional public Map<String,Object> completeTransfer(Long id){TransferOrder t=transfer(id);if(!"APPROVED".equals(t.getStatus()))throw new BusinessException("只有已审核调拨单可执行");for(TransferLine l:t.getLines())inventory.transfer(t.getTransferNo(),l.getItem().getCode(),t.getSourceWarehouse().getId(),l.getSourceLocationCode(),t.getTargetWarehouse().getId(),l.getTargetLocationCode(),l.getBatchNo(),l.getQuantity(),t.getRemark());t.setStatus("COMPLETED");return transferView(t);}
 @Transactional public Map<String,Object> createStocktake(StocktakeRequest r){Warehouse warehouse=warehouse(r.warehouseId());StocktakeOrder s=new StocktakeOrder();s.setStocktakeNo(numbers.next("PD"));s.setWarehouse(warehouse);s.setRemark(r.remark());List<StocktakeLine> lines=inventories.findAllDetailed().stream().filter(x->x.getWarehouse().getId().equals(warehouse.getId())).map(x->{StocktakeLine l=new StocktakeLine();l.setItem(x.getItem());l.setLocationCode(x.getLocation()==null?"DEFAULT":x.getLocation().getCode());l.setBatchNo(normalizeBatch(x.getBatchNo()));l.setBookQuantity(x.getQuantity());return l;}).toList();if(lines.isEmpty())throw new BusinessException("该仓库没有可盘点库存");s.replaceLines(lines);return stocktakeView(stocktakes.save(s));}
 @Transactional public Map<String,Object> countStocktake(Long id,StocktakeRequest r){StocktakeOrder s=stocktake(id);if(!"DRAFT".equals(s.getStatus()))throw new BusinessException("仅草稿盘点单可录入实盘数量");Map<String,BigDecimal> counts=new HashMap<>();if(r.lines()!=null)r.lines().forEach(x->counts.put(stockKey(x.itemCode(),x.locationCode(),x.batchNo()),x.actualQuantity()));s.getLines().forEach(l->{BigDecimal actual=counts.get(stockKey(l.getItem().getCode(),l.getLocationCode(),l.getBatchNo()));if(actual!=null){l.setActualQuantity(actual);l.setDifferenceQuantity(actual.subtract(l.getBookQuantity()));}});return stocktakeView(s);}
 @Transactional public Map<String,Object> reviewStocktake(Long id,ReviewRequest r){StocktakeOrder s=stocktake(id);ensureAdmin();if(!"DRAFT".equals(s.getStatus()))throw new BusinessException("只有草稿盘点单可审核");if(!Set.of("APPROVE","REJECT").contains(r.action()))throw new BusinessException("审核动作必须为 APPROVE 或 REJECT");s.setStatus("APPROVE".equals(r.action())?"APPROVED":"REJECTED");s.setReviewer(username());return stocktakeView(s);}
 @Transactional public Map<String,Object> completeStocktake(Long id){StocktakeOrder s=stocktake(id);if(!"APPROVED".equals(s.getStatus()))throw new BusinessException("只有已审核盘点单可执行");for(StocktakeLine l:s.getLines()){if(l.getActualQuantity()==null)throw new BusinessException("请先录入所有实盘数量");inventory.adjust(s.getStocktakeNo(),l.getItem().getCode(),s.getWarehouse().getId(),l.getLocationCode(),l.getBatchNo(),l.getActualQuantity(),s.getRemark());}s.setStatus("COMPLETED");return stocktakeView(s);}
 public List<Map<String,Object>> documents(){return docs.findAllDetailed().stream().map(this::documentView).toList();} public Map<String,Object> documentDetail(Long id){return documentView(document(id));} public List<Map<String,Object>> transferList(){return transfers.findAllDetailed().stream().map(this::transferView).toList();}public List<Map<String,Object>> stocktakeList(){return stocktakes.findAllDetailed().stream().map(this::stocktakeView).toList();}
 private BusinessPartner partner(String documentType,Long id){BusinessPartner partner=partners.findById(id).orElseThrow(()->new BusinessException("往来单位不存在"));if(!Boolean.TRUE.equals(partner.getEnabled()))throw new BusinessException("往来单位已停用");String expected="IN".equals(documentType)?"SUPPLIER":"CUSTOMER";if(!expected.equals(partner.getType())&&!"BOTH".equals(partner.getType()))throw new BusinessException("IN".equals(documentType)?"入库单只能选择供应商":"出库单只能选择客户");return partner;}private StockDocument document(Long id){return docs.findDetailedById(id).orElseThrow(()->new BusinessException("单据不存在"));}private TransferOrder transfer(Long id){return transfers.findDetailedById(id).orElseThrow(()->new BusinessException("调拨单不存在"));}private StocktakeOrder stocktake(Long id){return stocktakes.findDetailedById(id).orElseThrow(()->new BusinessException("盘点单不存在"));}private Item item(String code){return items.findByCode(code).orElseThrow(()->new BusinessException("物品不存在："+code));}private Warehouse warehouse(Long id){return warehouses.findById(id).orElseThrow(()->new BusinessException("仓库不存在"));}private String lineRemark(StockDocument d,StockDocumentLine l){return d.getRemark()==null?l.getRemark():d.getRemark();}
 private String normalizeBatch(String batchNo){return batchNo==null||batchNo.isBlank()?null:batchNo.trim();}private String stockKey(String itemCode,String locationCode,String batchNo){return itemCode+"@"+locationCode+"@"+Objects.toString(normalizeBatch(batchNo),"");}
 private String username(){Object p=SecurityContextHolder.getContext().getAuthentication().getPrincipal();return p instanceof com.wms.security.TokenService.Principal x?x.username():"system";}private void ensureAdmin(){Object p=SecurityContextHolder.getContext().getAuthentication().getPrincipal();if(!(p instanceof com.wms.security.TokenService.Principal x)||!"ADMIN".equals(x.role()))throw new AccessDeniedException("仅管理员可执行审核操作");}
 private Map<String,Object> documentView(StockDocument d){Map<String,Object> m=new LinkedHashMap<>();m.put("id",d.getId());m.put("documentNo",d.getDocumentNo());m.put("type",d.getType());m.put("status",d.getStatus());m.put("warehouseId",d.getWarehouse().getId());m.put("warehouseName",d.getWarehouse().getName());m.put("partnerId",d.getPartner()==null?null:d.getPartner().getId());m.put("partnerName",d.getPartner()==null?null:d.getPartner().getName());m.put("businessDate",d.getBusinessDate());m.put("remark",d.getRemark());m.put("reviewer",d.getReviewer());m.put("reviewRemark",d.getReviewRemark());m.put("createdAt",d.getCreatedAt());m.put("lines",d.getLines().stream().map(l->Map.of("id",l.getId(),"itemCode",l.getItem().getCode(),"itemName",l.getItem().getName(),"locationCode",l.getLocationCode(),"quantity",l.getQuantity(),"unitPrice",l.getUnitPrice(),"batchNo",l.getBatchNo()==null?"":l.getBatchNo())).toList());return m;}
 private Map<String,Object> transferView(TransferOrder t){Map<String,Object> m=new LinkedHashMap<>();m.put("id",t.getId());m.put("transferNo",t.getTransferNo());m.put("status",t.getStatus());m.put("sourceWarehouseId",t.getSourceWarehouse().getId());m.put("sourceWarehouseName",t.getSourceWarehouse().getName());m.put("targetWarehouseId",t.getTargetWarehouse().getId());m.put("targetWarehouseName",t.getTargetWarehouse().getName());m.put("remark",t.getRemark());m.put("reviewer",t.getReviewer());m.put("createdAt",t.getCreatedAt());m.put("lines",t.getLines().stream().map(l->Map.of("id",l.getId(),"itemCode",l.getItem().getCode(),"itemName",l.getItem().getName(),"sourceLocationCode",l.getSourceLocationCode(),"targetLocationCode",l.getTargetLocationCode(),"batchNo",l.getBatchNo()==null?"":l.getBatchNo(),"quantity",l.getQuantity())).toList());return m;}
 private Map<String,Object> stocktakeView(StocktakeOrder s){Map<String,Object> m=new LinkedHashMap<>();m.put("id",s.getId());m.put("stocktakeNo",s.getStocktakeNo());m.put("status",s.getStatus());m.put("warehouseId",s.getWarehouse().getId());m.put("warehouseName",s.getWarehouse().getName());m.put("remark",s.getRemark());m.put("reviewer",s.getReviewer());m.put("createdAt",s.getCreatedAt());m.put("lines",s.getLines().stream().map(l->{Map<String,Object> x=new LinkedHashMap<>();x.put("id",l.getId());x.put("itemCode",l.getItem().getCode());x.put("itemName",l.getItem().getName());x.put("locationCode",l.getLocationCode());x.put("batchNo",l.getBatchNo()==null?"":l.getBatchNo());x.put("bookQuantity",l.getBookQuantity());x.put("actualQuantity",l.getActualQuantity());x.put("differenceQuantity",l.getDifferenceQuantity());return x;}).toList());return m;}
}
