package com.wms.service;
import com.wms.common.BusinessException; import com.wms.dto.*; import com.wms.model.entity.*; import com.wms.repository.*; import com.wms.security.Permissions; import com.wms.security.SecurityUtils; import org.slf4j.Logger; import org.slf4j.LoggerFactory; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.BigDecimal; import java.util.*;

@Service public class DocumentService {
 private static final Logger log = LoggerFactory.getLogger(DocumentService.class);
 private final StockDocumentRepository docs; private final TransferOrderRepository transfers; private final StocktakeOrderRepository stocktakes; private final ItemRepository items; private final WarehouseRepository warehouses; private final BusinessPartnerRepository partners; private final InventoryRepository inventories; private final InventoryService inventory; private final DocumentNumberService numbers;
 public DocumentService(StockDocumentRepository docs,TransferOrderRepository transfers,StocktakeOrderRepository stocktakes,ItemRepository items,WarehouseRepository warehouses,BusinessPartnerRepository partners,InventoryRepository inventories,InventoryService inventory,DocumentNumberService numbers){this.docs=docs;this.transfers=transfers;this.stocktakes=stocktakes;this.items=items;this.warehouses=warehouses;this.partners=partners;this.inventories=inventories;this.inventory=inventory;this.numbers=numbers;}
 @Transactional public Map<String,Object> createDocument(DocumentRequest r){StockDocument d=new StockDocument();String prefix=switch(r.type()){case "IN"->"RKD";case "OUT"->"CKD";case "RETURN_IN"->"THI";case "RETURN_OUT"->"THO";default->throw new BusinessException("不支持的单据类型");};d.setDocumentNo(numbers.next(prefix));d.setType(r.type());d.setWarehouse(warehouse(r.warehouseId()));d.setPartner(r.partnerId()==null?null:partner(r.type(),r.partnerId()));d.setBusinessDate(r.businessDate()==null?java.time.LocalDate.now():r.businessDate());d.setRemark(r.remark());d.replaceLines(r.lines().stream().map(x->{StockDocumentLine l=new StockDocumentLine();l.setItem(item(x.itemCode()));l.setLocationCode(x.locationCode());l.setQuantity(x.quantity());l.setUnitPrice(x.unitPrice());l.setBatchNo(x.batchNo());l.setRemark(x.remark());return l;}).toList());log.info("单据创建: docNo={}, type={}, warehouseId={}", d.getDocumentNo(), r.type(), r.warehouseId());return documentView(docs.save(d));}
  @Transactional public Map<String,Object> reviewDocument(Long id,ReviewRequest r){StockDocument d=documentForUpdate(id);SecurityUtils.require(Permissions.DOCUMENT_REVIEW);if(!"DRAFT".equals(d.getStatus()))throw new BusinessException("只有草稿单可审核");if(!Set.of("APPROVE","REJECT").contains(r.action()))throw new BusinessException("审核动作必须为 APPROVE 或 REJECT");d.setStatus("APPROVE".equals(r.action())?"APPROVED":"REJECTED");d.setReviewer(username());d.setReviewRemark(r.remark());log.info("单据审核: docNo={}, action={}, reviewer={}", d.getDocumentNo(), r.action(), username());return documentView(d);}
 @Transactional public Map<String,Object> completeDocument(Long id){StockDocument d=documentForUpdate(id);if(!"APPROVED".equals(d.getStatus()))throw new BusinessException("只有已审核单据可执行");String t=d.getType();for(StockDocumentLine l:d.getLines()){boolean isIn=switch(t){case "IN","RETURN_IN"->true;case "OUT","RETURN_OUT"->false;default->throw new BusinessException("不支持的单据类型");};if(isIn)inventory.stockIn(new StockInRequest(l.getItem().getCode(),l.getQuantity(),l.getUnitPrice(),d.getWarehouse().getId(),l.getLocationCode(),l.getBatchNo(),lineRemark(d,l)),d.getDocumentNo(),switch(t){case "IN"->TransactionType.IN;default->TransactionType.RETURN_IN;});else inventory.stockOut(new StockOutRequest(l.getItem().getCode(),l.getQuantity(),l.getUnitPrice(),d.getWarehouse().getId(),l.getLocationCode(),l.getBatchNo(),lineRemark(d,l)),d.getDocumentNo(),switch(t){case "OUT"->TransactionType.OUT;default->TransactionType.RETURN_OUT;});}d.setStatus("COMPLETED");log.info("单据执行: docNo={}, type={}", d.getDocumentNo(), d.getType());return documentView(d);}
 @Transactional public Map<String,Object> cancelDocument(Long id){StockDocument d=documentForUpdate(id);SecurityUtils.require(Permissions.DOCUMENT_REVIEW);if("COMPLETED".equals(d.getStatus()))throw new BusinessException("已执行单据不可取消");d.setStatus("CANCELLED");return documentView(d);}
 /** 反审：把已执行(COMPLETED)单据记回 APPROVED，并生成反向库存流水冲销原库存影响。 */
  @Transactional public Map<String,Object> uncompleteDocument(Long id){StockDocument d=documentForUpdate(id);SecurityUtils.require(Permissions.DOCUMENT_REVIEW);if(!"COMPLETED".equals(d.getStatus()))throw new BusinessException("只有已执行单据可反审");reverseInventory(d);d.setStatus("APPROVED");d.setReviewer(username());log.info("单据反审: docNo={}", d.getDocumentNo());return documentView(d);}
/** 红冲：生成一张新的反向单据（type 互反、数量不变），原单据保持 COMPLETED。 */
  @Transactional public Map<String,Object> reverseDocument(Long id){StockDocument src=documentForUpdate(id);SecurityUtils.require(Permissions.DOCUMENT_REVIEW);if(!"COMPLETED".equals(src.getStatus()))throw new BusinessException("只有已执行单据可红冲");StockDocument d=new StockDocument();String t=switch(src.getType()){case "IN"->"OUT";case "OUT"->"IN";case "RETURN_IN"->"RETURN_OUT";case "RETURN_OUT"->"RETURN_IN";default->throw new BusinessException("不支持的原始单据类型");};String baseNo=numbers.next(switch(t){case "IN"->"RKD";case "OUT"->"CKD";case "RETURN_IN"->"THI";case "RETURN_OUT"->"THO";default->"CX";});String revNo=baseNo+".V";int suffix=1;while(docs.existsByDocumentNo(revNo)){revNo=baseNo+".V"+suffix++;}d.setDocumentNo(revNo);d.setType(t);d.setWarehouse(src.getWarehouse());d.setPartner(src.getPartner());d.setBusinessDate(java.time.LocalDate.now());d.setRemark((src.getRemark()==null?"":src.getRemark())+" 红冲自 "+src.getDocumentNo());d.replaceLines(src.getLines().stream().map(l->{StockDocumentLine nl=new StockDocumentLine();nl.setItem(l.getItem());nl.setLocationCode(l.getLocationCode());nl.setQuantity(l.getQuantity());nl.setUnitPrice(l.getUnitPrice());nl.setBatchNo(l.getBatchNo());nl.setRemark("红冲");return nl;}).toList());StockDocument saved=docs.save(d);saved.setStatus("APPROVED");docs.save(saved);return documentView(docs.save(saved));}
 private void reverseInventory(StockDocument d){String t=d.getType();for(StockDocumentLine l:d.getLines()){boolean wasIn=switch(t){case "IN","RETURN_IN"->true;case "OUT","RETURN_OUT"->false;default->throw new BusinessException("不支持的单据类型");};String ref="REV-"+d.getDocumentNo();if(wasIn)inventory.stockOut(new StockOutRequest(l.getItem().getCode(),l.getQuantity(),l.getUnitPrice(),d.getWarehouse().getId(),l.getLocationCode(),l.getBatchNo(),"反审冲销 "+d.getDocumentNo()),ref,TransactionType.REVERSE);else inventory.stockIn(new StockInRequest(l.getItem().getCode(),l.getQuantity(),l.getUnitPrice(),d.getWarehouse().getId(),l.getLocationCode(),l.getBatchNo(),"反审冲销 "+d.getDocumentNo()),ref,TransactionType.REVERSE);}}
 @Transactional public Map<String,Object> createTransfer(TransferRequest r){if(r.sourceWarehouseId().equals(r.targetWarehouseId()))throw new BusinessException("调出与调入仓库不能相同");TransferOrder t=new TransferOrder();t.setTransferNo(numbers.next("DBD"));t.setSourceWarehouse(warehouse(r.sourceWarehouseId()));t.setTargetWarehouse(warehouse(r.targetWarehouseId()));t.setRemark(r.remark());t.replaceLines(r.lines().stream().map(x->{TransferLine l=new TransferLine();l.setItem(item(x.itemCode()));l.setSourceLocationCode(x.sourceLocationCode());l.setTargetLocationCode(x.targetLocationCode());l.setBatchNo(normalizeBatch(x.batchNo()));l.setQuantity(x.quantity());return l;}).toList());return transferView(transfers.save(t));}
  @Transactional public Map<String,Object> reviewTransfer(Long id,ReviewRequest r){TransferOrder t=transferForUpdate(id);SecurityUtils.require(Permissions.TRANSFER_REVIEW);if(!"DRAFT".equals(t.getStatus()))throw new BusinessException("只有草稿调拨单可审核");if(!Set.of("APPROVE","REJECT").contains(r.action()))throw new BusinessException("审核动作必须为 APPROVE 或 REJECT");t.setStatus("APPROVE".equals(r.action())?"APPROVED":"REJECTED");t.setReviewer(username());return transferView(t);}
 @Transactional public Map<String,Object> completeTransfer(Long id){TransferOrder t=transferForUpdate(id);if(!"APPROVED".equals(t.getStatus()))throw new BusinessException("只有已审核调拨单可执行");for(TransferLine l:t.getLines())inventory.transfer(t.getTransferNo(),l.getItem().getCode(),t.getSourceWarehouse().getId(),l.getSourceLocationCode(),t.getTargetWarehouse().getId(),l.getTargetLocationCode(),l.getBatchNo(),l.getQuantity(),t.getRemark());t.setStatus("COMPLETED");return transferView(t);}
 @Transactional public Map<String,Object> createStocktake(StocktakeRequest r){Warehouse warehouse=warehouse(r.warehouseId());StocktakeOrder s=new StocktakeOrder();s.setStocktakeNo(numbers.next("PD"));s.setWarehouse(warehouse);s.setRemark(r.remark());Set<String> onlyItems=r.itemCodes()==null?null:new HashSet<>(r.itemCodes());Set<String> onlyLocs=r.locationCodes()==null?null:new HashSet<>(r.locationCodes());List<StocktakeLine> lines=inventories.findAllDetailed().stream().filter(x->x.getWarehouse().getId().equals(warehouse.getId())).filter(x->onlyItems==null||onlyItems.contains(x.getItem().getCode())).filter(x->onlyLocs==null||onlyLocs.contains(x.getLocation()==null?"":x.getLocation().getCode())).map(x->{StocktakeLine l=new StocktakeLine();l.setItem(x.getItem());l.setLocationCode(x.getLocation()==null?"":x.getLocation().getCode());l.setBatchNo(normalizeBatch(x.getBatchNo()));l.setBookQuantity(x.getQuantity());return l;}).toList();if(lines.isEmpty())throw new BusinessException("该仓库没有可盘点的库存（或所选过滤无匹配项）");s.replaceLines(lines);return stocktakeView(stocktakes.save(s));}
 @Transactional public Map<String,Object> countStocktake(Long id,StocktakeRequest r){StocktakeOrder s=stocktakeForUpdate(id);if(!"DRAFT".equals(s.getStatus()))throw new BusinessException("仅草稿盘点单可录入实盘数量");Map<String,BigDecimal> counts=new HashMap<>();if(r.lines()!=null)r.lines().forEach(x->counts.put(stockKey(x.itemCode(),x.locationCode(),x.batchNo()),x.actualQuantity()));s.getLines().forEach(l->{BigDecimal actual=counts.get(stockKey(l.getItem().getCode(),l.getLocationCode(),l.getBatchNo()));if(actual!=null){l.setActualQuantity(actual);l.setDifferenceQuantity(actual.subtract(l.getBookQuantity()));}});return stocktakeView(s);}
  @Transactional public Map<String,Object> reviewStocktake(Long id,ReviewRequest r){StocktakeOrder s=stocktakeForUpdate(id);SecurityUtils.require(Permissions.STOCKTAKE_REVIEW);if(!"DRAFT".equals(s.getStatus()))throw new BusinessException("只有草稿盘点单可审核");if(!Set.of("APPROVE","REJECT").contains(r.action()))throw new BusinessException("审核动作必须为 APPROVE 或 REJECT");s.setStatus("APPROVE".equals(r.action())?"APPROVED":"REJECTED");s.setReviewer(username());return stocktakeView(s);}
 @Transactional public Map<String,Object> completeStocktake(Long id){StocktakeOrder s=stocktakeForUpdate(id);if(!"APPROVED".equals(s.getStatus()))throw new BusinessException("只有已审核盘点单可执行");for(StocktakeLine l:s.getLines()){if(l.getActualQuantity()==null)throw new BusinessException("请先录入所有实盘数量");String loc=l.getLocationCode().isBlank()?null:l.getLocationCode();inventory.adjust(s.getStocktakeNo(),l.getItem().getCode(),s.getWarehouse().getId(),loc,l.getBatchNo(),l.getActualQuantity(),s.getRemark());}s.setStatus("COMPLETED");return stocktakeView(s);}
 public List<Map<String,Object>> documents(){return docs.findAllDetailed().stream().map(this::documentView).toList();} public Map<String,Object> documentDetail(Long id){return documentView(document(id));} public List<Map<String,Object>> transferList(){return transfers.findAllDetailed().stream().map(this::transferView).toList();}public List<Map<String,Object>> stocktakeList(){return stocktakes.findAllDetailed().stream().map(this::stocktakeView).toList();}
 private BusinessPartner partner(String documentType,Long id){BusinessPartner partner=partners.findById(id).orElseThrow(()->new BusinessException("往来单位不存在"));if(!Boolean.TRUE.equals(partner.getEnabled()))throw new BusinessException("往来单位已停用");String expected=switch(documentType){case "IN","RETURN_OUT"->"SUPPLIER";case "OUT","RETURN_IN"->"CUSTOMER";default->"IN".equals(documentType)?"SUPPLIER":"CUSTOMER";};if(!expected.equals(partner.getType())&&!"BOTH".equals(partner.getType()))throw new BusinessException(("IN".equals(documentType)||"RETURN_OUT".equals(documentType))?"该单位只能是供应商":"该单位只能是客户");return partner;}private StockDocument document(Long id){return docs.findDetailedById(id).orElseThrow(()->new BusinessException("单据不存在"));}
  private StockDocument documentForUpdate(Long id){return docs.findForUpdateById(id).orElseThrow(()->new BusinessException("单据不存在"));}private TransferOrder transfer(Long id){return transfers.findDetailedById(id).orElseThrow(()->new BusinessException("调拨单不存在"));}
  private TransferOrder transferForUpdate(Long id){return transfers.findForUpdateById(id).orElseThrow(()->new BusinessException("调拨单不存在"));}private StocktakeOrder stocktake(Long id){return stocktakes.findDetailedById(id).orElseThrow(()->new BusinessException("盘点单不存在"));}
  private StocktakeOrder stocktakeForUpdate(Long id){return stocktakes.findForUpdateById(id).orElseThrow(()->new BusinessException("盘点单不存在"));}private Item item(String code){return items.findByCode(code).orElseThrow(()->new BusinessException("物品不存在："+code));}private Warehouse warehouse(Long id){return warehouses.findById(id).orElseThrow(()->new BusinessException("仓库不存在"));}private String lineRemark(StockDocument d,StockDocumentLine l){return d.getRemark()==null?l.getRemark():d.getRemark();}
 private String normalizeBatch(String batchNo){return batchNo==null||batchNo.isBlank()?null:batchNo.trim();}private String stockKey(String itemCode,String locationCode,String batchNo){return itemCode+"@"+locationCode+"@"+Objects.toString(normalizeBatch(batchNo),"");}
 private String username(){return SecurityUtils.username();}
 private Map<String,Object> documentView(StockDocument d){Map<String,Object> m=new LinkedHashMap<>();m.put("id",d.getId());m.put("documentNo",d.getDocumentNo());m.put("type",d.getType());m.put("status",d.getStatus());m.put("warehouseId",d.getWarehouse().getId());m.put("warehouseName",d.getWarehouse().getName());m.put("partnerId",d.getPartner()==null?null:d.getPartner().getId());m.put("partnerName",d.getPartner()==null?null:d.getPartner().getName());m.put("businessDate",d.getBusinessDate());m.put("remark",d.getRemark());m.put("reviewer",d.getReviewer());m.put("reviewRemark",d.getReviewRemark());m.put("createdAt",d.getCreatedAt());m.put("lines",d.getLines().stream().map(l->Map.of("id",l.getId(),"itemCode",l.getItem().getCode(),"itemName",l.getItem().getName(),"locationCode",l.getLocationCode(),"quantity",l.getQuantity(),"unitPrice",l.getUnitPrice(),"batchNo",l.getBatchNo()==null?"":l.getBatchNo())).toList());return m;}
 private Map<String,Object> transferView(TransferOrder t){Map<String,Object> m=new LinkedHashMap<>();m.put("id",t.getId());m.put("transferNo",t.getTransferNo());m.put("status",t.getStatus());m.put("sourceWarehouseId",t.getSourceWarehouse().getId());m.put("sourceWarehouseName",t.getSourceWarehouse().getName());m.put("targetWarehouseId",t.getTargetWarehouse().getId());m.put("targetWarehouseName",t.getTargetWarehouse().getName());m.put("remark",t.getRemark());m.put("reviewer",t.getReviewer());m.put("createdAt",t.getCreatedAt());m.put("lines",t.getLines().stream().map(l->Map.of("id",l.getId(),"itemCode",l.getItem().getCode(),"itemName",l.getItem().getName(),"sourceLocationCode",l.getSourceLocationCode(),"targetLocationCode",l.getTargetLocationCode(),"batchNo",l.getBatchNo()==null?"":l.getBatchNo(),"quantity",l.getQuantity())).toList());return m;}
 private Map<String,Object> stocktakeView(StocktakeOrder s){Map<String,Object> m=new LinkedHashMap<>();m.put("id",s.getId());m.put("stocktakeNo",s.getStocktakeNo());m.put("status",s.getStatus());m.put("warehouseId",s.getWarehouse().getId());m.put("warehouseName",s.getWarehouse().getName());m.put("remark",s.getRemark());m.put("reviewer",s.getReviewer());m.put("createdAt",s.getCreatedAt());m.put("lines",s.getLines().stream().map(l->{Map<String,Object> x=new LinkedHashMap<>();x.put("id",l.getId());x.put("itemCode",l.getItem().getCode());x.put("itemName",l.getItem().getName());x.put("locationCode",l.getLocationCode());x.put("batchNo",l.getBatchNo()==null?"":l.getBatchNo());x.put("bookQuantity",l.getBookQuantity());x.put("actualQuantity",l.getActualQuantity());x.put("differenceQuantity",l.getDifferenceQuantity());return x;}).toList());return m;}
}
