package com.wms.service;

import com.wms.common.BusinessException;
import com.wms.dto.*;
import com.wms.model.entity.*;
import com.wms.repository.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.*; import java.time.*; import java.util.*;

@Service
public class InventoryService {
 private static final Logger log = LoggerFactory.getLogger(InventoryService.class);
  private final ItemRepository items; private final WarehouseRepository warehouses; private final LocationRepository locations; private final InventoryRepository inventories; private final InventoryTransactionRepository transactions; private final DocumentNumberService numbers; private final WarehouseAccessService warehouseAccess; private final InventoryReservationGuard reservationGuard;
  public InventoryService(ItemRepository items,WarehouseRepository warehouses,LocationRepository locations,InventoryRepository inventories,InventoryTransactionRepository transactions,DocumentNumberService numbers,WarehouseAccessService warehouseAccess,InventoryReservationGuard reservationGuard){this.items=items;this.warehouses=warehouses;this.locations=locations;this.inventories=inventories;this.transactions=transactions;this.numbers=numbers;this.warehouseAccess=warehouseAccess;this.reservationGuard=reservationGuard;}

 @Transactional public Map<String,Object> stockIn(StockInRequest request){return stockIn(request,null,TransactionType.IN);} @Transactional public Map<String,Object> stockIn(StockInRequest request,String referenceNo,String type){return stockIn(request,referenceNo,type,null,null,null);} @Transactional public Map<String,Object> stockIn(StockInRequest request,String referenceNo,String type,Long sourceDocumentId,Long sourceLineId,String operator){
  Item item=item(request.itemCode()); Warehouse warehouse=warehouse(request.warehouseId()); Location location=location(warehouse,request.locationCode(),true); String batchNo=request.batchNo()==null||request.batchNo().isBlank()?null:request.batchNo(); Inventory inventory=inventory(item,warehouse,location,batchNo,true);
  BigDecimal amount=InventoryCostCalculator.amount(request.quantity(),request.unitCost()); BigDecimal quantity=inventory.getQuantity().add(request.quantity()); BigDecimal total=inventory.getTotalAmount().add(amount); BigDecimal avg=InventoryCostCalculator.averageCost(inventory.getQuantity(),inventory.getTotalAmount(),request.quantity(),amount);
  inventory.setQuantity(quantity);inventory.setTotalAmount(total);inventory.setAvgCost(avg);inventory.setLastInCost(request.unitCost());inventories.save(inventory);
  String no=referenceNo==null?nextOrderNo("RK"):referenceNo; transaction(item,warehouse,location,batchNo,type,no,request.remark(),request.quantity(),request.unitCost(),amount,BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO,quantity,total,avg,sourceDocumentId,sourceLineId,null,operator);
  log.info("入库: item={}, warehouse={}, qty={}, cost={}, orderNo={}", request.itemCode(), request.warehouseId(), request.quantity(), request.unitCost(), no);
  return movementResult(no,item,request.quantity(),amount,avg,quantity,total,Map.of("unitCost",request.unitCost()));
 }
 @Transactional public Map<String,Object> stockOut(StockOutRequest request){return stockOut(request,null,TransactionType.OUT);}
 @Transactional public Map<String,Object> stockOut(StockOutRequest request,String referenceNo,String type){return stockOut(request,referenceNo,type,null,null,null);}
 @Transactional public Map<String,Object> stockOut(StockOutRequest request,String referenceNo,String type,Long sourceDocumentId,Long sourceLineId,String operator){
  Item item=item(request.itemCode()); Warehouse warehouse=warehouse(request.warehouseId()); Location location=location(warehouse,request.locationCode(),false); String batchNo=request.batchNo()==null||request.batchNo().isBlank()?null:request.batchNo(); InventoryReservationGuard.Snapshot protection=reservationGuard.lock(item.getId(),warehouse.getId());reservationGuard.requireAvailable(protection,null,request.quantity(),"库存不足或已被商城订单预占");Inventory inventory=inventory(item,warehouse,location,batchNo,false);
  if(inventory.getQuantity().compareTo(request.quantity())<0) throw new BusinessException("库存不足：可用 "+inventory.getQuantity().stripTrailingZeros().toPlainString()); BigDecimal unit=inventory.getAvgCost();BigDecimal cost=InventoryCostCalculator.amount(request.quantity(),unit);BigDecimal sales=InventoryCostCalculator.amount(request.quantity(),request.salePrice());BigDecimal profit=TransactionType.REVERSE.equals(type)?BigDecimal.ZERO.setScale(2):sales.subtract(cost).setScale(2,RoundingMode.HALF_UP);BigDecimal quantity=inventory.getQuantity().subtract(request.quantity());BigDecimal total=inventory.getTotalAmount().subtract(cost).max(BigDecimal.ZERO).setScale(2,RoundingMode.HALF_UP);BigDecimal avg=quantity.signum()==0?BigDecimal.ZERO.setScale(4):unit;
  inventory.setQuantity(quantity);inventory.setTotalAmount(total);inventory.setAvgCost(avg);inventories.save(inventory);String no=referenceNo==null?nextOrderNo("CK"):referenceNo;transaction(item,warehouse,location,batchNo,type,no,request.remark(),request.quantity().negate(),unit,cost,request.salePrice(),sales,profit,quantity,total,avg,sourceDocumentId,sourceLineId,null,operator);
  log.info("出库: item={}, warehouse={}, qty={}, salePrice={}, profit={}, orderNo={}", request.itemCode(), request.warehouseId(), request.quantity(), request.salePrice(), profit, no);
  return movementResult(no,item,request.quantity(),cost,avg,quantity,total,Map.of("costUnit",unit,"salePrice",request.salePrice(),"saleAmount",sales,"profit",profit));
 }
 @Transactional public void transfer(String referenceNo,String itemCode,Long sourceWarehouseId,String sourceLocationCode,Long targetWarehouseId,String targetLocationCode,String batchNo,BigDecimal quantity,String remark){
  Item item=item(itemCode); Warehouse source=warehouse(sourceWarehouseId);Warehouse target=warehouse(targetWarehouseId);Location from=location(source,sourceLocationCode,false);Location to=location(target,targetLocationCode,true);String normalizedBatch=normalizeBatch(batchNo);InventoryReservationGuard.Snapshot protection=reservationGuard.lock(item.getId(),source.getId());reservationGuard.requireAvailable(protection,null,quantity,"调拨库存不足或已被商城订单预占："+itemCode);Inventory sourceInv=inventory(item,source,from,normalizedBatch,false);if(sourceInv.getQuantity().compareTo(quantity)<0)throw new BusinessException("调拨库存不足："+itemCode);
  BigDecimal unit=sourceInv.getAvgCost(),amount=InventoryCostCalculator.amount(quantity,unit),sourceQty=sourceInv.getQuantity().subtract(quantity),sourceTotal=sourceInv.getTotalAmount().subtract(amount).max(BigDecimal.ZERO).setScale(2,RoundingMode.HALF_UP),sourceAvg=sourceQty.signum()==0?BigDecimal.ZERO.setScale(4):unit;
  sourceInv.setQuantity(sourceQty);sourceInv.setTotalAmount(sourceTotal);sourceInv.setAvgCost(sourceAvg);inventories.save(sourceInv);transaction(item,source,from,normalizedBatch,TransactionType.TRANSFER_OUT,referenceNo,remark,quantity.negate(),unit,amount,BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO,sourceQty,sourceTotal,sourceAvg);
  Inventory targetInv=inventory(item,target,to,normalizedBatch,true);BigDecimal targetQty=targetInv.getQuantity().add(quantity),targetTotal=targetInv.getTotalAmount().add(amount),targetAvg=InventoryCostCalculator.transferAverageCost(targetInv.getQuantity(),targetInv.getTotalAmount(),quantity,unit);targetInv.setQuantity(targetQty);targetInv.setTotalAmount(targetTotal);targetInv.setAvgCost(targetAvg);targetInv.setLastInCost(unit);inventories.save(targetInv);transaction(item,target,to,normalizedBatch,TransactionType.TRANSFER_IN,referenceNo,remark,quantity,unit,amount,BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO,targetQty,targetTotal,targetAvg);
  log.info("调拨: item={}, fromWarehouse={}, toWarehouse={}, qty={}, orderNo={}", itemCode, sourceWarehouseId, targetWarehouseId, quantity, referenceNo);
 }
 @Transactional public void adjust(String referenceNo,String itemCode,Long warehouseId,String locationCode,String batchNo,BigDecimal actualQuantity,String remark){adjust(referenceNo,itemCode,warehouseId,locationCode,batchNo,actualQuantity,remark,null);}
 @Transactional public void adjust(String referenceNo,String itemCode,Long warehouseId,String locationCode,String batchNo,BigDecimal actualQuantity,String remark,Long expectedVersion){
  Item item=item(itemCode); Warehouse warehouse=warehouse(warehouseId); Location location=location(warehouse,locationCode,true); String normalizedBatch=normalizeBatch(batchNo); InventoryReservationGuard.Snapshot protection=reservationGuard.lock(item.getId(),warehouse.getId());Inventory inv=inventory(item,warehouse,location,normalizedBatch,true);if(expectedVersion!=null&&!Objects.equals(expectedVersion,inv.getVersion()))throw new BusinessException("账面库存已变化，请重新盘点");BigDecimal delta=actualQuantity.subtract(inv.getQuantity());if(delta.signum()==0)return;if(delta.signum()<0)reservationGuard.requirePhysicalAfter(protection,protection.physical().subtract(inv.getQuantity()).add(actualQuantity),"盘点调整会减少商城已预占库存");BigDecimal unit=inv.getAvgCost(),amount=InventoryCostCalculator.amount(delta.abs(),unit),qty=actualQuantity,total=delta.signum()>0?inv.getTotalAmount().add(amount):inv.getTotalAmount().subtract(amount).max(BigDecimal.ZERO).setScale(2,RoundingMode.HALF_UP),avg=qty.signum()==0?BigDecimal.ZERO.setScale(4):unit;inv.setQuantity(qty);inv.setTotalAmount(total);inv.setAvgCost(avg);inventories.save(inv);transaction(item,warehouse,location,normalizedBatch,delta.signum()>0?TransactionType.ADJUST_IN:TransactionType.ADJUST_OUT,referenceNo,remark,delta,unit,amount,BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO,qty,total,avg);
  log.info("盘点调整: item={}, warehouse={}, delta={}, actual={}, orderNo={}", itemCode, warehouseId, delta, actualQuantity, referenceNo);
 }
 /** 按未冲销的原库存流水逐笔反向入/出，不使用当前均价或销售价重新核算。 */
 @Transactional public void reverseDocumentTransactions(String originalReferenceNo,String reversalReferenceNo,Long sourceDocumentId,String operator){List<InventoryTransaction> originals=transactions.findUnreversedByReferenceNo(originalReferenceNo);if(originals.isEmpty())throw new BusinessException("原单缺少可冲销库存流水");for(InventoryTransaction original:originals){if(original.getQuantity()==null||original.getQuantity().signum()==0)continue;boolean reverseIn=original.getQuantity().signum()<0;InventoryReservationGuard.Snapshot protection=reverseIn?null:reservationGuard.lock(original.getItem().getId(),original.getWarehouse().getId());Inventory inv=inventories.findForUpdate(original.getItem().getId(),original.getWarehouse().getId(),original.getLocation()==null?null:original.getLocation().getId(),original.getBatchNo()).orElseThrow(()->new BusinessException("原库存记录不存在，无法冲销："+original.getId()));BigDecimal quantity=original.getQuantity().abs(),cost=original.getTotalCostAmount()==null?BigDecimal.ZERO.setScale(2):original.getTotalCostAmount();BigDecimal newQty,newTotal,newAvg;if(reverseIn){newQty=inv.getQuantity().add(quantity);newTotal=inv.getTotalAmount().add(cost).setScale(2,RoundingMode.HALF_UP);newAvg=InventoryCostCalculator.averageCost(inv.getQuantity(),inv.getTotalAmount(),quantity,cost);inv.setLastInCost(original.getUnitCost());}else{if(inv.getQuantity().compareTo(quantity)<0||inv.getTotalAmount().compareTo(cost)<0)throw new BusinessException("后续库存已发生变化，无法安全冲销原入库流水："+original.getId());reservationGuard.requirePhysicalAfter(protection,protection.physical().subtract(quantity),"冲销将消耗商城已预占库存："+original.getId());newQty=inv.getQuantity().subtract(quantity);newTotal=inv.getTotalAmount().subtract(cost).setScale(2,RoundingMode.HALF_UP);newAvg=newQty.signum()==0?BigDecimal.ZERO.setScale(4):newTotal.divide(newQty,4,RoundingMode.HALF_UP);}inv.setQuantity(newQty);inv.setTotalAmount(newTotal);inv.setAvgCost(newAvg);inventories.save(inv);transaction(original.getItem(),original.getWarehouse(),original.getLocation(),original.getBatchNo(),reverseIn?TransactionType.REVERSE_IN:TransactionType.REVERSE_OUT,reversalReferenceNo,"冲销 "+originalReferenceNo,original.getQuantity().negate(),original.getUnitCost(),cost,BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO,newQty,newTotal,newAvg,original.getSourceDocumentId()==null?sourceDocumentId:original.getSourceDocumentId(),original.getSourceLineId(),original.getId(),operator);}}
 private String normalizeBatch(String batchNo){return batchNo==null||batchNo.isBlank()?null:batchNo.trim();}
 private Item item(String code){return items.findByCode(code).orElseThrow(()->new BusinessException("未找到物品编码："+code));} private Warehouse warehouse(Long id){warehouseAccess.require(id);Warehouse wh=warehouses.findById(id).orElseThrow(()->new BusinessException("仓库不存在"));if(!Boolean.TRUE.equals(wh.getStatus()))throw new BusinessException("仓库已禁用");return wh;}
  private Location location(Warehouse warehouse,String code,boolean create){Optional<Location> found=locations.findByWarehouseIdAndCode(warehouse.getId(),code);if(found.isPresent())return found.get();if(!create)throw new BusinessException("库位不存在："+code);locations.insertIfAbsent(warehouse.getId(),code);return locations.findByWarehouseIdAndCode(warehouse.getId(),code).orElseThrow();}
 private Inventory inventory(Item item,Warehouse warehouse,Location location,String batchNo,boolean create){Optional<Inventory> existing=inventories.findForUpdate(item.getId(),warehouse.getId(),location.getId(),batchNo);if(existing.isPresent())return existing.get();if(!create)throw new BusinessException("该库位没有库存");items.findForInventoryCreation(item.getId()).orElseThrow(()->new BusinessException("物品不存在"));return inventories.findForUpdate(item.getId(),warehouse.getId(),location.getId(),batchNo).orElseGet(()->new Inventory(item,warehouse,location,batchNo));}
 private void transaction(Item item,Warehouse warehouse,Location location,String batchNo,String type,String ref,String remark,BigDecimal quantity,BigDecimal unit,BigDecimal cost,BigDecimal salePrice,BigDecimal saleAmount,BigDecimal profit,BigDecimal balanceQty,BigDecimal balanceAmount,BigDecimal avg){transaction(item,warehouse,location,batchNo,type,ref,remark,quantity,unit,cost,salePrice,saleAmount,profit,balanceQty,balanceAmount,avg,null,null,null,null);}
 private void transaction(Item item,Warehouse warehouse,Location location,String batchNo,String type,String ref,String remark,BigDecimal quantity,BigDecimal unit,BigDecimal cost,BigDecimal salePrice,BigDecimal saleAmount,BigDecimal profit,BigDecimal balanceQty,BigDecimal balanceAmount,BigDecimal avg,Long sourceDocumentId,Long sourceLineId,Long reversalOfTransactionId,String operator){InventoryTransaction t=new InventoryTransaction();t.setItem(item);t.setWarehouse(warehouse);t.setLocation(location);t.setBatchNo(batchNo);t.setTransactionType(type);t.setReferenceNo(ref);t.setRemark(remark);t.setQuantity(quantity);t.setUnitCost(unit);t.setTotalCostAmount(cost);t.setSalePrice(salePrice);t.setSaleAmount(saleAmount);t.setProfit(profit);t.setBalanceQuantity(balanceQty);t.setBalanceAmount(balanceAmount);t.setAvgCostAfter(avg);t.setSourceDocumentId(sourceDocumentId);t.setSourceLineId(sourceLineId);t.setReversalOfTransactionId(reversalOfTransactionId);t.setOperator(operator);transactions.save(t);}
 private Map<String,Object> movementResult(String no,Item item,BigDecimal qty,BigDecimal amount,BigDecimal avg,BigDecimal stock,BigDecimal stockAmount,Map<String,Object> extra){Map<String,Object> r=new LinkedHashMap<>();r.put("orderNo",no);r.put("itemCode",item.getCode());r.put("itemName",item.getName());r.put("quantity",qty);r.put("totalAmount",amount);r.put("newAvgCost",avg);r.put("newStockQuantity",stock);r.put("newStockAmount",stockAmount);r.putAll(extra);return r;}
  private String nextOrderNo(String prefix){return numbers.next(prefix);}
}
