package com.wms.service;
import com.wms.common.BusinessException; import com.wms.dto.*; import com.wms.model.entity.*; import com.wms.repository.*; import com.wms.security.Permissions; import com.wms.security.SecurityUtils; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service public class PurchaseRequestService { private final PurchaseRequestRepository requests; private final ItemRepository items; private final WarehouseRepository warehouses; private final BusinessPartnerRepository partners; private final DocumentNumberService numbers; private final WarehouseAccessService warehouseAccess; public PurchaseRequestService(PurchaseRequestRepository r,ItemRepository i,WarehouseRepository w,BusinessPartnerRepository p,DocumentNumberService n,WarehouseAccessService warehouseAccess){requests=r;items=i;warehouses=w;partners=p;numbers=n;this.warehouseAccess=warehouseAccess;}
 @Transactional public Map<String,Object> create(PurchaseRequestRequest r){PurchaseRequest p=new PurchaseRequest();p.setRequestNo(numbers.next("CGSQ"));p.setWarehouse(warehouse(r.warehouseId()));p.setSupplier(r.supplierId()==null?null:partners.findById(r.supplierId()).orElseThrow(()->new BusinessException("供应商不存在")));p.setRequiredDate(r.requiredDate());p.setSource(r.source()==null?"MANUAL":r.source());p.setRemark(r.remark());p.setApplicant(username());p.replaceLines(r.lines().stream().map(x->{PurchaseRequestLine l=new PurchaseRequestLine();l.setItem(items.findByCode(x.itemCode()).orElseThrow(()->new BusinessException("物品不存在："+x.itemCode())));l.setQuantity(x.quantity());l.setSuggestedQuantity(x.suggestedQuantity());l.setCurrentStock(x.currentStock());l.setUnitPrice(x.unitPrice());l.setRemark(x.remark());return l;}).toList());return view(requests.save(p));}
 @Transactional public Map<String,Object> review(Long id,ReviewRequest r){PurchaseRequest p=getForUpdate(id);SecurityUtils.require(Permissions.PURCHASE_REVIEW);if(!"DRAFT".equals(p.getStatus()))throw new BusinessException("只有草稿采购申请可审核");if(!Set.of("APPROVE","REJECT").contains(r.action()))throw new BusinessException("审核动作必须为 APPROVE 或 REJECT");p.setStatus("APPROVE".equals(r.action())?"APPROVED":"REJECTED");p.setReviewer(username());p.setReviewRemark(r.remark());return view(p);}
 @Transactional public Map<String,Object> cancel(Long id){PurchaseRequest p=getForUpdate(id);SecurityUtils.require(Permissions.PURCHASE_WRITE);if(!Set.of("DRAFT","REJECTED").contains(p.getStatus()))throw new BusinessException("当前状态不可取消");p.setStatus("CANCELLED");return view(p);}
 public Map<String,Object> list(int page,int pageSize){boolean scoped=warehouseAccess.isWarehouseScoped();List<Long> warehouseIds=scoped?warehouseAccess.currentWarehouseIds():List.of(-1L);org.springframework.data.domain.Page<Long> ids=requests.pageIds(scoped,warehouseIds,org.springframework.data.domain.PageRequest.of(Math.max(0,page-1),Math.min(100,Math.max(1,pageSize))));List<PurchaseRequest> details=ids.getContent().isEmpty()?List.of():requests.findDetailedByIdIn(ids.getContent());Map<Long,PurchaseRequest> byId=details.stream().collect(java.util.stream.Collectors.toMap(PurchaseRequest::getId,x->x));List<Map<String,Object>> records=ids.getContent().stream().map(byId::get).filter(Objects::nonNull).map(this::view).toList();return Map.of("records",records,"total",ids.getTotalElements(),"page",ids.getNumber()+1,"pageSize",ids.getSize());} private PurchaseRequest getForUpdate(Long id){PurchaseRequest p=requests.findForUpdateById(id).orElseThrow(()->new BusinessException("采购申请不存在"));warehouseAccess.require(p.getWarehouse().getId());return p;}
 private Map<String,Object> view(PurchaseRequest p){Map<String,Object> m=new LinkedHashMap<>();m.put("id",p.getId());m.put("requestNo",p.getRequestNo());m.put("status",p.getStatus());m.put("source",p.getSource());m.put("warehouseId",p.getWarehouse().getId());m.put("warehouseName",p.getWarehouse().getName());m.put("supplierId",p.getSupplier()==null?null:p.getSupplier().getId());m.put("supplierName",p.getSupplier()==null?null:p.getSupplier().getName());m.put("requiredDate",p.getRequiredDate());m.put("applicant",p.getApplicant());m.put("reviewer",p.getReviewer());m.put("reviewRemark",p.getReviewRemark());m.put("remark",p.getRemark());m.put("lines",p.getLines().stream().map(l->{Map<String,Object>x=new LinkedHashMap<>();x.put("itemCode",l.getItem().getCode());x.put("itemName",l.getItem().getName());x.put("currentStock",l.getCurrentStock());x.put("suggestedQuantity",l.getSuggestedQuantity());x.put("quantity",l.getQuantity());x.put("unitPrice",l.getUnitPrice());return x;}).toList());return m;}
 private Warehouse warehouse(Long id){warehouseAccess.require(id);return warehouses.findById(id).orElseThrow(()->new BusinessException("仓库不存在"));}private String username(){return SecurityUtils.username();} }
