-- Baseline for the schema that existed before Flyway was introduced.
-- New installations apply this file and later deltas. Existing installations
-- are baselined at V1 by application-prod.yml before receiving later deltas.

create table adjustment_lines (quantity decimal(18,4) not null, adjustment_id bigint not null, created_at datetime(6) not null, id bigint not null auto_increment, item_id bigint not null, updated_at datetime(6) not null, batch_no varchar(60), location_code varchar(255) not null, primary key (id)) engine=InnoDB;
create table adjustment_orders (created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6) not null, warehouse_id bigint not null, action varchar(20) not null, status varchar(20) not null, adjustment_no varchar(60) not null, reason varchar(255), remark varchar(255), reviewer varchar(255), primary key (id)) engine=InnoDB;
create table business_partners (enabled bit not null, created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6) not null, type varchar(20) not null, code varchar(50) not null, name varchar(200) not null, remark varchar(1000), address varchar(255), contact_name varchar(255), email varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table categories (sort_order integer, status bit, created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table document_sequences (counter bigint not null, created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6) not null, prefix varchar(20) not null, primary key (id)) engine=InnoDB;
create table inventory (avg_cost decimal(18,4) not null, last_in_cost decimal(18,4) not null, quantity decimal(18,4) not null, total_amount decimal(18,2) not null, created_at datetime(6) not null, id bigint not null auto_increment, item_id bigint not null, location_id bigint, updated_at datetime(6) not null, warehouse_id bigint not null, batch_no varchar(60), primary key (id)) engine=InnoDB;
create table inventory_transactions (avg_cost_after decimal(18,4) not null, balance_amount decimal(18,2) not null, balance_quantity decimal(18,4) not null, profit decimal(18,2), quantity decimal(18,4) not null, sale_amount decimal(18,2), sale_price decimal(18,4), total_cost_amount decimal(18,2) not null, unit_cost decimal(18,4) not null, created_at datetime(6) not null, id bigint not null auto_increment, item_id bigint not null, location_id bigint, transaction_at datetime(6) not null, updated_at datetime(6) not null, warehouse_id bigint not null, batch_no varchar(60), reference_no varchar(255) not null, remark varchar(255), transaction_type varchar(255) not null, primary key (id)) engine=InnoDB;
create table items (max_stock decimal(18,4) not null, min_stock decimal(18,4) not null, safety_stock decimal(18,4) not null, status bit not null, category_id bigint, created_at datetime(6) not null, default_warehouse_id bigint, id bigint not null auto_increment, updated_at datetime(6) not null, code varchar(50) not null, name varchar(200) not null, remark varchar(1000), barcode varchar(255), brand varchar(255), model varchar(255), specs varchar(255), unit varchar(255), primary key (id)) engine=InnoDB;
create table locations (status bit, created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6) not null, warehouse_id bigint not null, code varchar(255) not null, primary key (id)) engine=InnoDB;
create table market_cart (quantity integer not null, snapshot_price decimal(18,4) not null, created_at datetime(6) not null, id bigint not null auto_increment, product_id bigint not null, updated_at datetime(6) not null, user_account_id bigint not null, primary key (id)) engine=InnoDB;
create table market_customer (default_flag bit not null, created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6) not null, user_account_id bigint, phone varchar(20) not null, name varchar(60) not null, address varchar(200) not null, remark varchar(200), primary key (id)) engine=InnoDB;
create table market_favorite (created_at datetime(6) not null, id bigint not null auto_increment, product_id bigint not null, updated_at datetime(6) not null, user_account_id bigint not null, primary key (id)) engine=InnoDB;
create table market_order (refund_amount decimal(18,2), total_amount decimal(18,2) not null, audited_at datetime(6), cancelled_at datetime(6), completed_at datetime(6), created_at datetime(6) not null, customer_id bigint, id bigint not null auto_increment, paid_at datetime(6), refunded_at datetime(6), shipped_at datetime(6), updated_at datetime(6) not null, user_account_id bigint not null, warehouse_id bigint not null, receiver_phone varchar(20) not null, order_no varchar(32) not null, transaction_id varchar(32), receiver_name varchar(60) not null, prepay_id varchar(64), refund_no varchar(64), refund_reason varchar(80), logistics_company varchar(100), logistics_number varchar(100), receiver_address varchar(200) not null, admin_remark varchar(500), remark varchar(500), cancel_reason varchar(255), review_remark varchar(255), reviewer varchar(255), order_status enum ('AUDITED','CANCELLED','COMPLETED','PENDING','REJECTED','SHIPPED') not null, pay_status enum ('PAID','REFUNDED','REFUNDING','UNPAID') not null, pay_type enum ('CASH_ON_DELIVERY','CREDIT','PAY_ONLINE') not null, primary key (id)) engine=InnoDB;
create table market_order_item (quantity decimal(18,2) not null, sale_price decimal(18,4) not null, subtotal decimal(18,2) not null, created_at datetime(6) not null, id bigint not null auto_increment, item_id bigint not null, order_id bigint not null, product_id bigint not null, updated_at datetime(6) not null, unit varchar(30), item_code varchar(200) not null, item_name varchar(200) not null, primary key (id)) engine=InnoDB;
create table market_order_log (created_at datetime(6) not null, id bigint not null auto_increment, order_id bigint not null, updated_at datetime(6) not null, operator varchar(60), remark varchar(500), action enum ('AUDIT','CANCEL','COMPLETE','CREATE','PAY','REFUND','SHIP') not null, primary key (id)) engine=InnoDB;
create table market_product (market_price decimal(18,4), sale_price decimal(18,4) not null, sort_no integer not null, category_id bigint, created_at datetime(6) not null, id bigint not null auto_increment, item_id bigint not null, sales_count bigint not null, updated_at datetime(6) not null, view_count bigint not null, status varchar(20) not null, title varchar(200) not null, main_image varchar(500), sub_title varchar(500), gallery varchar(2000), primary key (id)) engine=InnoDB;
create table operation_logs (id bigint not null auto_increment, operation_at datetime(6) not null, method varchar(20), action varchar(50) not null, username varchar(50) not null, path varchar(200), target varchar(200), message varchar(500), request_body varchar(255), result varchar(255), primary key (id)) engine=InnoDB;
create table purchase_request_lines (current_stock decimal(18,4) not null, quantity decimal(18,4) not null, suggested_quantity decimal(18,4) not null, unit_price decimal(18,4), id bigint not null auto_increment, item_id bigint not null, request_id bigint not null, remark varchar(255), primary key (id)) engine=InnoDB;
create table purchase_requests (required_date date, created_at datetime(6) not null, id bigint not null auto_increment, supplier_id bigint, updated_at datetime(6) not null, warehouse_id bigint not null, source varchar(20) not null, status varchar(20) not null, request_no varchar(60) not null, applicant varchar(255), remark varchar(255), review_remark varchar(255), reviewer varchar(255), primary key (id)) engine=InnoDB;
create table stock_document_lines (quantity decimal(18,4) not null, unit_price decimal(18,4) not null, created_at datetime(6) not null, document_id bigint not null, id bigint not null auto_increment, item_id bigint not null, updated_at datetime(6) not null, batch_no varchar(255), location_code varchar(255) not null, remark varchar(255), primary key (id)) engine=InnoDB;
create table stock_documents (business_date date, created_at datetime(6) not null, id bigint not null auto_increment, partner_id bigint, updated_at datetime(6) not null, warehouse_id bigint not null, type varchar(10) not null, status varchar(20) not null, document_no varchar(60) not null, remark varchar(255), review_remark varchar(255), reviewer varchar(255), primary key (id)) engine=InnoDB;
create table stocktake_lines (actual_quantity decimal(18,4), book_quantity decimal(18,4) not null, difference_quantity decimal(18,4), created_at datetime(6) not null, id bigint not null auto_increment, item_id bigint not null, stocktake_id bigint not null, updated_at datetime(6) not null, batch_no varchar(60), location_code varchar(255) not null, primary key (id)) engine=InnoDB;
create table stocktake_orders (created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6) not null, warehouse_id bigint not null, remark varchar(255), reviewer varchar(255), status varchar(255) not null, stocktake_no varchar(255) not null, primary key (id)) engine=InnoDB;
create table transfer_lines (quantity decimal(18,4) not null, created_at datetime(6) not null, id bigint not null auto_increment, item_id bigint not null, transfer_id bigint not null, updated_at datetime(6) not null, batch_no varchar(60), source_location_code varchar(255) not null, target_location_code varchar(255) not null, primary key (id)) engine=InnoDB;
create table transfer_orders (created_at datetime(6) not null, id bigint not null auto_increment, source_warehouse_id bigint not null, target_warehouse_id bigint not null, updated_at datetime(6) not null, remark varchar(255), reviewer varchar(255), status varchar(255) not null, transfer_no varchar(255) not null, primary key (id)) engine=InnoDB;
create table user_accounts (enabled bit not null, created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6) not null, role varchar(30) not null, username varchar(50) not null, openid varchar(64), display_name varchar(255), password varchar(255) not null, primary key (id)) engine=InnoDB;
create table warehouses (status bit, created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6) not null, code varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;

alter table adjustment_orders add constraint uk_adjustment_orders_no unique (adjustment_no);
alter table business_partners add constraint uk_business_partners_code unique (code);
alter table document_sequences add constraint uk_document_sequences_prefix unique (prefix);
alter table inventory add constraint uk_inventory_key unique (item_id, warehouse_id, location_id, batch_no);
alter table items add constraint uk_items_code unique (code);
alter table locations add constraint uk_locations_warehouse_code unique (warehouse_id, code);
alter table market_cart add constraint uk_market_cart_user_product unique (user_account_id, product_id);
alter table market_favorite add constraint uk_market_favorite_user_product unique (user_account_id, product_id);
alter table market_order add constraint uk_market_order_no unique (order_no);
alter table market_product add constraint uk_market_product_item unique (item_id);
alter table purchase_requests add constraint uk_purchase_requests_no unique (request_no);
alter table stock_documents add constraint uk_stock_documents_no unique (document_no);
alter table stocktake_orders add constraint uk_stocktake_orders_no unique (stocktake_no);
alter table transfer_orders add constraint uk_transfer_orders_no unique (transfer_no);
alter table user_accounts add constraint uk_user_accounts_username unique (username);
alter table user_accounts add constraint uk_user_accounts_openid unique (openid);
alter table warehouses add constraint uk_warehouses_code unique (code);

alter table adjustment_lines add constraint fk_adjustment_lines_order foreign key (adjustment_id) references adjustment_orders (id);
alter table adjustment_lines add constraint fk_adjustment_lines_item foreign key (item_id) references items (id);
alter table adjustment_orders add constraint fk_adjustment_orders_warehouse foreign key (warehouse_id) references warehouses (id);
alter table inventory add constraint fk_inventory_item foreign key (item_id) references items (id);
alter table inventory add constraint fk_inventory_location foreign key (location_id) references locations (id);
alter table inventory add constraint fk_inventory_warehouse foreign key (warehouse_id) references warehouses (id);
alter table inventory_transactions add constraint fk_transactions_item foreign key (item_id) references items (id);
alter table inventory_transactions add constraint fk_transactions_location foreign key (location_id) references locations (id);
alter table inventory_transactions add constraint fk_transactions_warehouse foreign key (warehouse_id) references warehouses (id);
alter table items add constraint fk_items_category foreign key (category_id) references categories (id);
alter table items add constraint fk_items_warehouse foreign key (default_warehouse_id) references warehouses (id);
alter table locations add constraint fk_locations_warehouse foreign key (warehouse_id) references warehouses (id);
alter table market_cart add constraint fk_market_cart_product foreign key (product_id) references market_product (id);
alter table market_cart add constraint fk_market_cart_user foreign key (user_account_id) references user_accounts (id);
alter table market_customer add constraint fk_market_customer_user foreign key (user_account_id) references user_accounts (id);
alter table market_favorite add constraint fk_market_favorite_product foreign key (product_id) references market_product (id);
alter table market_favorite add constraint fk_market_favorite_user foreign key (user_account_id) references user_accounts (id);
alter table market_order add constraint fk_market_order_customer foreign key (customer_id) references market_customer (id);
alter table market_order add constraint fk_market_order_user foreign key (user_account_id) references user_accounts (id);
alter table market_order add constraint fk_market_order_warehouse foreign key (warehouse_id) references warehouses (id);
alter table market_order_item add constraint fk_market_order_item_item foreign key (item_id) references items (id);
alter table market_order_item add constraint fk_market_order_item_order foreign key (order_id) references market_order (id);
alter table market_product add constraint fk_market_product_category foreign key (category_id) references categories (id);
alter table market_product add constraint fk_market_product_item foreign key (item_id) references items (id);
alter table purchase_request_lines add constraint fk_purchase_request_lines_item foreign key (item_id) references items (id);
alter table purchase_request_lines add constraint fk_purchase_request_lines_request foreign key (request_id) references purchase_requests (id);
alter table purchase_requests add constraint fk_purchase_requests_supplier foreign key (supplier_id) references business_partners (id);
alter table purchase_requests add constraint fk_purchase_requests_warehouse foreign key (warehouse_id) references warehouses (id);
alter table stock_document_lines add constraint fk_stock_document_lines_document foreign key (document_id) references stock_documents (id);
alter table stock_document_lines add constraint fk_stock_document_lines_item foreign key (item_id) references items (id);
alter table stock_documents add constraint fk_stock_documents_partner foreign key (partner_id) references business_partners (id);
alter table stock_documents add constraint fk_stock_documents_warehouse foreign key (warehouse_id) references warehouses (id);
alter table stocktake_lines add constraint fk_stocktake_lines_item foreign key (item_id) references items (id);
alter table stocktake_lines add constraint fk_stocktake_lines_order foreign key (stocktake_id) references stocktake_orders (id);
alter table stocktake_orders add constraint fk_stocktake_orders_warehouse foreign key (warehouse_id) references warehouses (id);
alter table transfer_lines add constraint fk_transfer_lines_item foreign key (item_id) references items (id);
alter table transfer_lines add constraint fk_transfer_lines_order foreign key (transfer_id) references transfer_orders (id);
alter table transfer_orders add constraint fk_transfer_orders_source_warehouse foreign key (source_warehouse_id) references warehouses (id);
alter table transfer_orders add constraint fk_transfer_orders_target_warehouse foreign key (target_warehouse_id) references warehouses (id);
