package com.wms.model.entity;
import jakarta.persistence.*;
import java.math.BigDecimal; import java.time.LocalDateTime;
@Entity @Table(name="inventory_transactions")
public class InventoryTransaction extends AuditableEntity {
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Long id;
 @ManyToOne(optional=false,fetch=FetchType.LAZY) private Item item; @ManyToOne(optional=false,fetch=FetchType.LAZY) private Warehouse warehouse; @ManyToOne(fetch=FetchType.LAZY) private Location location;
 @Column(nullable=false) private String transactionType; @Column(nullable=false) private String referenceNo; private String remark;
 @Column(nullable=false,precision=18,scale=4) private BigDecimal quantity; @Column(nullable=false,precision=18,scale=4) private BigDecimal unitCost;
 @Column(nullable=false,precision=18,scale=2) private BigDecimal totalCostAmount; @Column(precision=18,scale=4) private BigDecimal salePrice=BigDecimal.ZERO; @Column(precision=18,scale=2) private BigDecimal saleAmount=BigDecimal.ZERO; @Column(precision=18,scale=2) private BigDecimal profit=BigDecimal.ZERO;
 @Column(nullable=false,precision=18,scale=4) private BigDecimal balanceQuantity; @Column(nullable=false,precision=18,scale=2) private BigDecimal balanceAmount; @Column(nullable=false,precision=18,scale=4) private BigDecimal avgCostAfter; @Column(nullable=false) private LocalDateTime transactionAt=LocalDateTime.now();
 public InventoryTransaction(){} public Long getId(){return id;} public Item getItem(){return item;} public void setItem(Item x){item=x;} public Warehouse getWarehouse(){return warehouse;} public void setWarehouse(Warehouse x){warehouse=x;} public Location getLocation(){return location;} public void setLocation(Location x){location=x;} public String getTransactionType(){return transactionType;} public void setTransactionType(String x){transactionType=x;} public String getReferenceNo(){return referenceNo;} public void setReferenceNo(String x){referenceNo=x;} public String getRemark(){return remark;} public void setRemark(String x){remark=x;} public BigDecimal getQuantity(){return quantity;} public void setQuantity(BigDecimal x){quantity=x;} public BigDecimal getUnitCost(){return unitCost;} public void setUnitCost(BigDecimal x){unitCost=x;} public BigDecimal getTotalCostAmount(){return totalCostAmount;} public void setTotalCostAmount(BigDecimal x){totalCostAmount=x;} public BigDecimal getSalePrice(){return salePrice;} public void setSalePrice(BigDecimal x){salePrice=x;} public BigDecimal getSaleAmount(){return saleAmount;} public void setSaleAmount(BigDecimal x){saleAmount=x;} public BigDecimal getProfit(){return profit;} public void setProfit(BigDecimal x){profit=x;} public BigDecimal getBalanceQuantity(){return balanceQuantity;} public void setBalanceQuantity(BigDecimal x){balanceQuantity=x;} public BigDecimal getBalanceAmount(){return balanceAmount;} public void setBalanceAmount(BigDecimal x){balanceAmount=x;} public BigDecimal getAvgCostAfter(){return avgCostAfter;} public void setAvgCostAfter(BigDecimal x){avgCostAfter=x;} public LocalDateTime getTransactionAt(){return transactionAt;}
}
