package com.wms.controller;
import com.wms.dto.StockOutRequest; import com.wms.harness.Harness; import com.wms.model.entity.Inventory; import com.wms.model.entity.InventoryTransaction; import com.wms.repository.InventoryRepository; import com.wms.repository.InventoryTransactionRepository; import com.wms.service.InventoryService; import org.junit.jupiter.api.Test; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.test.context.ActiveProfiles; import org.springframework.transaction.annotation.Transactional; import java.math.BigDecimal; import java.time.LocalDate; import java.time.LocalDateTime; import java.time.format.DateTimeFormatter; import java.util.*; import static org.junit.jupiter.api.Assertions.*;
@SpringBootTest @ActiveProfiles("test") @Transactional class ReportControllerIntegrationTest {
 @Autowired private ReportController reports; @Autowired private InventoryService inventory; @Autowired private InventoryTransactionRepository transactions; @Autowired private InventoryRepository inventories; @Autowired private com.wms.service.WarehouseAccessService warehouseAccess;
 @Test void inOutSummaryRebuildsHistoricalPeriodInsteadOfReadingCurrentInventory(){Harness.asAdmin(()->{LocalDate period=LocalDate.now().minusMonths(2).withDayOfMonth(1);InventoryTransaction seed=transactions.findRecentDetailed().stream().filter(t->"ITEM-001".equals(t.getItem().getCode())&&"in".equals(t.getTransactionType())).findFirst().orElseThrow();seed.setTransactionAt(period.plusDays(2).atStartOfDay());transactions.saveAndFlush(seed);inventory.stockOut(new StockOutRequest("ITEM-001",new BigDecimal("10"),new BigDecimal("99"),1L,"A-01-01",null,"本月后出库"));List<Map<String,Object>> rows=reports.inOutSummary(period.format(DateTimeFormatter.ofPattern("yyyy-MM"))).data();Map<String,Object> row=rows.stream().filter(x->"ITEM-001".equals(x.get("itemCode"))).findFirst().orElseThrow();assertEquals(0,new BigDecimal("100").compareTo((BigDecimal)row.get("inQuantity")));assertEquals(0,BigDecimal.ZERO.compareTo((BigDecimal)row.get("outQuantity")));assertEquals(0,new BigDecimal("100").compareTo((BigDecimal)row.get("endingQuantity")));BigDecimal live=inventories.findAllDetailed().stream().filter(i->"ITEM-001".equals(i.getItem().getCode())).map(Inventory::getQuantity).reduce(BigDecimal.ZERO,BigDecimal::add);assertEquals(0,new BigDecimal("90").compareTo(live));});}
 @Test void dashboardSeparatesSalesFromAllOutboundCostAndCountsUniqueItems(){Harness.asAdmin(()->{inventory.stockOut(new StockOutRequest("ITEM-001",new BigDecimal("2"),new BigDecimal("99"),1L,"A-01-01",null,"销售"));Map<String,Object> data=reports.dashboard().data();assertEquals(0,new BigDecimal("198.00").compareTo((BigDecimal)data.get("todaySalesAmount")));assertEquals(0,new BigDecimal("31.00").compareTo((BigDecimal)data.get("todayOutboundAmount")));long expected=inventories.findAllDetailed().stream().filter(i->i.getQuantity().signum()>0).map(i->i.getItem().getId()).distinct().count();assertEquals(expected,((Number)data.get("stockItemCount")).longValue());});}
 @Test void inventoryAgeConsumesOldestLayersWithinTheSameBatch(){Harness.asAdmin(()->{InventoryTransaction seed=transactions.findRecentDetailed().stream().filter(t->"ITEM-001".equals(t.getItem().getCode())&&"in".equals(t.getTransactionType())).findFirst().orElseThrow();seed.setTransactionAt(LocalDateTime.now().minusDays(100));transactions.saveAndFlush(seed);inventory.stockOut(new StockOutRequest("ITEM-001",new BigDecimal("80"),new BigDecimal("99"),1L,"A-01-01",null,"消耗旧层"));inventory.stockIn(new com.wms.dto.StockInRequest("ITEM-001",new BigDecimal("20"),new BigDecimal("15.50"),1L,"A-01-01",null,"补入新层"));Map<String,Object> row=reports.inventoryAge().data().stream().filter(x->"ITEM-001".equals(x.get("itemCode"))).findFirst().orElseThrow();assertEquals(50L,((Number)row.get("ageDays")).longValue());assertEquals("30-60",row.get("bucket"));});}
 /** 库龄缓存（#4）：TTL 内同范围复用同一结果（含库存变动也不穿透），关闭后立即重算。 */
 @Test void inventoryAgeCachesByScopeUntilTtlOrDisabled(){Harness.asAdmin(()->{org.springframework.test.util.ReflectionTestUtils.setField(reports,"inventoryAgeCacheSeconds",300);List<Map<String,Object>> first=reports.inventoryAge().data();assertSame(first,reports.inventoryAge().data(),"TTL 内第二次调用应命中缓存");inventory.stockOut(new StockOutRequest("ITEM-001",new BigDecimal("1"),new BigDecimal("99"),1L,"A-01-01",null,"TTL 内变动不应穿透缓存"));assertSame(first,reports.inventoryAge().data(),"库存变动后 TTL 内仍应命中缓存");org.springframework.test.util.ReflectionTestUtils.setField(reports,"inventoryAgeCacheSeconds",0);assertNotSame(first,reports.inventoryAge().data(),"关闭缓存后应立即重算");});}
 /** R4-01：仓库受限用户的 dashboard 最近流水必须全部落在授权仓库内（此前未过滤+缓存放大）。 */
 @Test void dashboardRecentTransactionsRespectWarehouseScope(){com.wms.security.TokenService.Principal principal=new com.wms.security.TokenService.Principal("operator","WAREHOUSE","库管",com.wms.security.RolePermissions.forRole("WAREHOUSE"));org.springframework.security.core.context.SecurityContextHolder.getContext().setAuthentication(new org.springframework.security.authentication.UsernamePasswordAuthenticationToken(principal,null,com.wms.security.RolePermissions.forRole("WAREHOUSE").stream().map(org.springframework.security.core.authority.SimpleGrantedAuthority::new).toList()));try{Map<String,Object> data=reports.dashboard().data();Set<Long> allowed=new HashSet<>(warehouseAccess.currentWarehouseIds());@SuppressWarnings("unchecked")List<Map<String,Object>> recent=(List<Map<String,Object>>)data.get("recentTransactions");for(Map<String,Object> t:recent){Long wid=((Number)t.get("warehouseId")).longValue();assertTrue(allowed.contains(wid),"越权：dashboard 出现授权仓库之外的流水 warehouseId="+wid);}}finally{org.springframework.security.core.context.SecurityContextHolder.clearContext();}}
 /** 仪表盘缓存（L4）：TTL 内同范围复用同一结果（含库存变动也不穿透），关闭后立即重算。 */
 @Test void dashboardCachesByScopeUntilTtlOrDisabled(){Harness.asAdmin(()->{org.springframework.test.util.ReflectionTestUtils.setField(reports,"dashboardCacheSeconds",300);Map<String,Object> first=reports.dashboard().data();assertSame(first,reports.dashboard().data(),"TTL 内第二次调用应命中缓存");inventory.stockOut(new StockOutRequest("ITEM-001",new BigDecimal("1"),new BigDecimal("99"),1L,"A-01-01",null,"TTL 内变动不应穿透缓存"));assertSame(first,reports.dashboard().data(),"库存变动后 TTL 内仍应命中缓存");org.springframework.test.util.ReflectionTestUtils.setField(reports,"dashboardCacheSeconds",0);assertNotSame(first,reports.dashboard().data(),"关闭缓存后应立即重算");});}
}
