package com.wms.controller;
import com.wms.common.*; import com.wms.dto.LoginRequest; import com.wms.dto.UserRequest; import com.wms.model.entity.UserAccount; import com.wms.repository.UserAccountRepository; import com.wms.security.TokenService; import jakarta.validation.Valid; import org.slf4j.Logger; import org.slf4j.LoggerFactory; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.security.access.AccessDeniedException; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/auth") public class AuthController {
 private static final Logger log = LoggerFactory.getLogger(AuthController.class);
 private final UserAccountRepository users; private final PasswordEncoder encoder; private final TokenService tokens;
 public AuthController(UserAccountRepository users,PasswordEncoder encoder,TokenService tokens){this.users=users;this.encoder=encoder;this.tokens=tokens;}
 @PostMapping("/login") public ApiResponse<Map<String,Object>> login(@Valid @RequestBody LoginRequest request){UserAccount user=users.findByUsername(request.username().trim()).orElseThrow(()->new BusinessException("用户名或密码错误"));if(!Boolean.TRUE.equals(user.getEnabled())||!encoder.matches(request.password(),user.getPassword()))throw new BusinessException("用户名或密码错误");String token=tokens.issue(user);log.info("登录成功: username={}, role={}", user.getUsername(), user.getRole());return ApiResponse.ok("登录成功",view(user,token));}
 @GetMapping("/me") public ApiResponse<Map<String,Object>> me(){Object p=SecurityContextHolder.getContext().getAuthentication().getPrincipal();if(!(p instanceof TokenService.Principal principal))throw new BusinessException("登录状态已失效");return ApiResponse.ok(Map.of("username",principal.username(),"role",principal.role(),"displayName",principal.displayName()==null?principal.username():principal.displayName()));}
 @GetMapping("/users") public ApiResponse<List<Map<String,Object>>> users(){ensureAdmin();return ApiResponse.ok(users.findAll().stream().map(u->userView(u)).toList());}
 @PostMapping("/users") public ApiResponse<Map<String,Object>> createUser(@Valid @RequestBody UserRequest request){ensureAdmin();if(users.findByUsername(request.username().trim()).isPresent())throw new BusinessException("用户名已存在");if(request.password()==null||request.password().length()<6)throw new BusinessException("密码至少 6 位");UserAccount u=new UserAccount();u.setUsername(request.username().trim());u.setPassword(encoder.encode(request.password()));u.setDisplayName(request.displayName());u.setRole(request.role());u.setEnabled(request.enabled()==null||request.enabled());return ApiResponse.ok("用户创建成功",userView(users.save(u)));}
 @PutMapping("/users/{id}") public ApiResponse<Map<String,Object>> updateUser(@PathVariable Long id,@Valid @RequestBody UserRequest request){ensureAdmin();UserAccount u=users.findById(id).orElseThrow(()->new BusinessException("用户不存在"));u.setDisplayName(request.displayName());u.setRole(request.role());u.setEnabled(request.enabled()==null||request.enabled());if(request.password()!=null&&!request.password().isBlank()){if(request.password().length()<6)throw new BusinessException("密码至少 6 位");u.setPassword(encoder.encode(request.password()));}return ApiResponse.ok("用户更新成功",userView(users.save(u)));}
 @PostMapping("/logout") public ApiResponse<Void> logout(@RequestHeader(value="Authorization",required=false) String auth){if(auth!=null&&auth.startsWith("Bearer ")){tokens.revoke(auth.substring(7));log.info("用户退出登录");}return ApiResponse.ok("已退出登录",null);}
 private void ensureAdmin(){Object p=SecurityContextHolder.getContext().getAuthentication().getPrincipal();if(!(p instanceof TokenService.Principal principal)||!"ADMIN".equals(principal.role()))throw new AccessDeniedException("仅管理员可管理用户");}
 private Map<String,Object> userView(UserAccount u){return Map.of("id",u.getId(),"username",u.getUsername(),"displayName",u.getDisplayName()==null?u.getUsername():u.getDisplayName(),"role",u.getRole(),"enabled",u.getEnabled());}
 private Map<String,Object> view(UserAccount u,String token){Map<String,Object> m=new LinkedHashMap<>();m.put("token",token);m.put("username",u.getUsername());m.put("displayName",u.getDisplayName());m.put("role",u.getRole());m.put("expiresIn",43200);return m;}
}
