package com.wms.controller;
import com.wms.common.*; import com.wms.model.entity.*; import com.wms.repository.*; import org.apache.poi.ss.usermodel.*; import org.apache.poi.xssf.usermodel.XSSFWorkbook; import org.springframework.http.*; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import java.io.*; import java.math.BigDecimal; import java.net.URLEncoder; import java.nio.charset.StandardCharsets; import java.util.*;
@RestController @RequestMapping("/excel") public class ExcelController {
 private final ItemRepository items; private final CategoryRepository categories; public ExcelController(ItemRepository items,CategoryRepository categories){this.items=items;this.categories=categories;}
 @GetMapping("/items/export") public ResponseEntity<byte[]> exportItems()throws IOException{try(Workbook wb=new XSSFWorkbook();ByteArrayOutputStream out=new ByteArrayOutputStream()){Sheet sheet=wb.createSheet("物品档案");String[] heads={"物品编码","物品名称","分类","单位","规格型号","安全库存","最小库存","最大库存","备注"};Row header=sheet.createRow(0);for(int i=0;i<heads.length;i++)header.createCell(i).setCellValue(heads[i]);int row=1;for(Item item:items.findAll()){Row r=sheet.createRow(row++);put(r,0,item.getCode());put(r,1,item.getName());put(r,2,item.getCategory()==null?"":item.getCategory().getName());put(r,3,item.getUnit());put(r,4,item.getSpecs());put(r,5,item.getSafetyStock());put(r,6,item.getMinStock());put(r,7,item.getMaxStock());put(r,8,item.getRemark());}for(int i=0;i<heads.length;i++)sheet.autoSizeColumn(i);wb.write(out);String filename=URLEncoder.encode("物品档案.xlsx",StandardCharsets.UTF_8).replace("+","%20");return ResponseEntity.ok().header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename*=UTF-8''"+filename).contentType(MediaType.parseMediaType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")).body(out.toByteArray());}}
 /** 导入物品档案：任一行数据非法则整单回滚（@Transactional），并给出具体行号错误，避免"部分成功"与静默置零。 */
 @PostMapping(value="/items/import",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) @Transactional public ApiResponse<Map<String,Object>> importItems(@RequestPart("file") MultipartFile file)throws IOException{if(file.isEmpty())throw new BusinessException("请选择 Excel 文件");int created=0,updated=0,skipped=0;try(Workbook wb=WorkbookFactory.create(file.getInputStream())){Sheet sheet=wb.getSheetAt(0);for(int i=1;i<=sheet.getLastRowNum();i++){Row row=sheet.getRow(i);if(row==null)continue;String code=text(row,0),name=text(row,1);if(code.isBlank()||name.isBlank()){skipped++;continue;}Item item=items.findByCode(code).orElseGet(Item::new);boolean exists=item.getId()!=null;item.setCode(code);item.setName(name);String categoryName=text(row,2);if(!categoryName.isBlank())item.setCategory(categories.findByName(categoryName).orElseGet(() -> categories.save(new Category(categoryName))));item.setUnit(blank(text(row,3),"个"));item.setSpecs(text(row,4));item.setSafetyStock(decimal(text(row,5),i));item.setMinStock(decimal(text(row,6),i));item.setMaxStock(decimal(text(row,7),i));item.setRemark(text(row,8));item.setStatus(true);items.save(item);if(exists)updated++;else created++;}}return ApiResponse.ok("导入完成",Map.of("created",created,"updated",updated,"skipped",skipped));}
 private void put(Row row,int index,Object value){row.createCell(index).setCellValue(value==null?"":String.valueOf(value));}private String text(Row row,int i){Cell c=row.getCell(i);if(c==null)return "";DataFormatter f=new DataFormatter();return f.formatCellValue(c).trim();}private String blank(String a,String b){return a.isBlank()?b:a;}
 private BigDecimal decimal(String value,int rowNum){if(value.isBlank())return BigDecimal.ZERO;try{return new BigDecimal(value);}catch(NumberFormatException e){throw new BusinessException("第 "+(rowNum+1)+" 行数字格式不正确: \""+value+"\"");}}
}
