package com.wms.controller;
import com.wms.common.*; import com.wms.dto.ItemRequest; import com.wms.model.entity.*; import com.wms.repository.*; import jakarta.validation.Valid; import org.springframework.data.domain.*; import org.springframework.web.bind.annotation.*; import java.time.*; import java.util.*;
@RestController @RequestMapping("/items")
public class ItemController {
 private final ItemRepository items; private final CategoryRepository categories; private final WarehouseRepository warehouses;
 public ItemController(ItemRepository items,CategoryRepository categories,WarehouseRepository warehouses){this.items=items;this.categories=categories;this.warehouses=warehouses;}
 @GetMapping public ApiResponse<Map<String,Object>> list(@RequestParam(defaultValue="1") int page,@RequestParam(defaultValue="10") int pageSize,@RequestParam(required=false) String keyword){Pageable pageable=PageRequest.of(Math.max(0,page-1),Math.min(100,Math.max(1,pageSize)),Sort.by("id").descending());Page<Item> result=(keyword==null||keyword.isBlank())?items.findAll(pageable):items.findByNameContainingIgnoreCaseOrCodeContainingIgnoreCase(keyword,keyword,pageable);return ApiResponse.ok(page(result));}
 @GetMapping("/{id}") public ApiResponse<Map<String,Object>> get(@PathVariable Long id){return ApiResponse.ok(view(items.findById(id).orElseThrow(()->new BusinessException("物品不存在"))));}
 @GetMapping("/code/{code}") public ApiResponse<Map<String,Object>> getByCode(@PathVariable String code){return ApiResponse.ok(view(items.findByCode(code).orElseThrow(()->new BusinessException("物品不存在"))));}
 @PostMapping public ApiResponse<Map<String,Object>> create(@Valid @RequestBody ItemRequest request){if(items.existsByCode(request.code()))throw new BusinessException("物品编码已存在");return ApiResponse.ok("新增物品成功",view(items.save(merge(new Item(),request))));}
 @PutMapping("/{id}") public ApiResponse<Map<String,Object>> update(@PathVariable Long id,@Valid @RequestBody ItemRequest request){Item item=items.findById(id).orElseThrow(()->new BusinessException("物品不存在"));if(!item.getCode().equals(request.code())&&items.existsByCode(request.code()))throw new BusinessException("物品编码已存在");return ApiResponse.ok("更新物品成功",view(items.save(merge(item,request))));}
 @DeleteMapping("/{id}") public ApiResponse<Void> delete(@PathVariable Long id){if(!items.existsById(id))throw new BusinessException("物品不存在");items.deleteById(id);return ApiResponse.ok("删除物品成功",null);}
 @GetMapping("/categories") public ApiResponse<List<Map<String,Object>>> categoryList(){return ApiResponse.ok(categories.findAll().stream().map(c->Map.<String,Object>of("id",c.getId(),"name",c.getName())).toList());}
 private Item merge(Item item,ItemRequest r){item.setCode(r.code().trim());item.setName(r.name().trim());item.setUnit(r.unit()==null||r.unit().isBlank()?"个":r.unit());item.setSpecs(r.specs());item.setBrand(r.brand());item.setModel(r.model());item.setBarcode(r.barcode());item.setSafetyStock(r.safetyStock());item.setMaxStock(r.maxStock());item.setMinStock(r.minStock());item.setStatus(r.status()==null||r.status());item.setRemark(r.remark());item.setCategory(r.categoryId()==null?null:categories.findById(r.categoryId()).orElseThrow(()->new BusinessException("物品分类不存在")));item.setDefaultWarehouse(r.defaultWarehouseId()==null?null:warehouses.findById(r.defaultWarehouseId()).orElseThrow(()->new BusinessException("仓库不存在")));return item;}
 private Map<String,Object> page(Page<Item> p){return Map.of("records",p.getContent().stream().map(ItemController::view).toList(),"total",p.getTotalElements(),"page",p.getNumber()+1,"pageSize",p.getSize());}
 public static Map<String,Object> view(Item item){Map<String,Object> map=new LinkedHashMap<>();map.put("id",item.getId());map.put("code",item.getCode());map.put("name",item.getName());map.put("categoryId",item.getCategory()==null?null:item.getCategory().getId());map.put("categoryName",item.getCategory()==null?null:item.getCategory().getName());map.put("defaultWarehouseId",item.getDefaultWarehouse()==null?null:item.getDefaultWarehouse().getId());map.put("defaultWarehouseName",item.getDefaultWarehouse()==null?null:item.getDefaultWarehouse().getName());map.put("unit",item.getUnit());map.put("specs",item.getSpecs());map.put("brand",item.getBrand());map.put("model",item.getModel());map.put("barcode",item.getBarcode());map.put("safetyStock",item.getSafetyStock());map.put("maxStock",item.getMaxStock());map.put("minStock",item.getMinStock());map.put("status",item.getStatus());map.put("remark",item.getRemark());map.put("createdAt",item.getCreatedAt());return map;}
}
