package com.wms.controller;
import com.wms.common.*; import com.wms.dto.PartnerRequest; import com.wms.model.entity.BusinessPartner; import com.wms.repository.BusinessPartnerRepository; import com.wms.repository.PurchaseRequestRepository; import com.wms.repository.StockDocumentRepository; import jakarta.validation.Valid; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/partners") public class PartnerController {
 private final BusinessPartnerRepository partners; private final StockDocumentRepository documents; private final PurchaseRequestRepository purchaseRequests;
 public PartnerController(BusinessPartnerRepository partners,StockDocumentRepository documents,PurchaseRequestRepository purchaseRequests){this.partners=partners;this.documents=documents;this.purchaseRequests=purchaseRequests;}
 @GetMapping public ApiResponse<List<Map<String,Object>>> list(@RequestParam(required=false) String type){List<BusinessPartner> values=(type==null||type.isBlank())?partners.findAll():partners.findByTypeInAndEnabledTrueOrderByName(List.of(type,"BOTH"));return ApiResponse.ok(values.stream().map(PartnerController::view).toList());}
 @PostMapping public ApiResponse<Map<String,Object>> create(@Valid @RequestBody PartnerRequest r){if(partners.existsByCode(r.code().trim()))throw new BusinessException("往来单位编码已存在");return ApiResponse.ok("新增往来单位成功",view(partners.save(merge(new BusinessPartner(),r))));}
 @PutMapping("/{id}") public ApiResponse<Map<String,Object>> update(@PathVariable Long id,@Valid @RequestBody PartnerRequest r){BusinessPartner p=partners.findById(id).orElseThrow(()->new BusinessException("往来单位不存在"));if(!p.getCode().equals(r.code().trim())&&partners.existsByCode(r.code().trim()))throw new BusinessException("往来单位编码已存在");return ApiResponse.ok("更新成功",view(partners.save(merge(p,r))));}
  @DeleteMapping("/{id}") public ApiResponse<Void> delete(@PathVariable Long id){BusinessPartner p=partners.findById(id).orElseThrow(()->new BusinessException("往来单位不存在"));if(documents.existsByPartnerId(id))throw new BusinessException("该单位已被单据引用，不可删除");if(purchaseRequests.existsBySupplierId(id))throw new BusinessException("该单位已被采购申请引用，不可删除");partners.delete(p);return ApiResponse.ok("删除成功",null);}
 private BusinessPartner merge(BusinessPartner p,PartnerRequest r){p.setCode(r.code().trim());p.setName(r.name().trim());p.setType(r.type());p.setContactName(r.contactName());p.setPhone(r.phone());p.setEmail(r.email());p.setAddress(r.address());p.setEnabled(r.enabled()==null||r.enabled());p.setRemark(r.remark());return p;}
 public static Map<String,Object> view(BusinessPartner p){Map<String,Object> m=new LinkedHashMap<>();m.put("id",p.getId());m.put("code",p.getCode());m.put("name",p.getName());m.put("type",p.getType());m.put("contactName",p.getContactName());m.put("phone",p.getPhone());m.put("email",p.getEmail());m.put("address",p.getAddress());m.put("enabled",p.getEnabled());m.put("remark",p.getRemark());return m;}
}
