import client from './client'
export const api = {
  login: (data) => client.post('/auth/login', data), me: () => client.get('/auth/me'), logout: () => client.post('/auth/logout'), users: () => client.get('/auth/users'), createUser: (data) => client.post('/auth/users', data), updateUser: (id,data) => client.put(`/auth/users/${id}`, data),
  dashboard: () => client.get('/reports/dashboard'), alerts: () => client.get('/reports/stock-alert'), profit: () => client.get('/reports/profit'),
  items: (params) => client.get('/items', { params }), item: (id) => client.get(`/items/${id}`), createItem: (data) => client.post('/items', data), updateItem: (id, data) => client.put(`/items/${id}`, data), deleteItem: (id) => client.delete(`/items/${id}`), categories: () => client.get('/items/categories'),
  inventory: () => client.get('/inventory'), inventoryByItem: (itemId) => client.get(`/inventory/${itemId}`), transactions: () => client.get('/inventory/transactions'), warehouses: (includeDisabled = false) => client.get('/warehouses', { params: includeDisabled ? { includeDisabled: true } : {} }), createWarehouse: (data) => client.post('/warehouses', data), updateWarehouse: (id, data) => client.put(`/warehouses/${id}`, data),
  stockIn: (data) => client.post('/stock/in/scan', data), stockOut: (data) => client.post('/stock/out/scan', data),
  partners: (type) => client.get('/partners', { params: type ? { type } : {} }), createPartner: (data) => client.post('/partners', data), updatePartner: (id,data) => client.put(`/partners/${id}`,data), deletePartner: (id) => client.delete(`/partners/${id}`),
  documents: () => client.get('/documents'), document: (id) => client.get(`/documents/${id}`), createDocument: (data) => client.post('/documents',data), reviewDocument: (id,data) => client.post(`/documents/${id}/review`,data), completeDocument: (id) => client.post(`/documents/${id}/complete`), cancelDocument: (id) => client.post(`/documents/${id}/cancel`),
  transfers: () => client.get('/transfers'), createTransfer: (data) => client.post('/transfers',data), reviewTransfer: (id,data) => client.post(`/transfers/${id}/review`,data), completeTransfer: (id) => client.post(`/transfers/${id}/complete`),
  stocktakes: () => client.get('/stocktakes'), createStocktake: (data) => client.post('/stocktakes',data), countStocktake: (id,data) => client.post(`/stocktakes/${id}/count`,data), reviewStocktake: (id,data) => client.post(`/stocktakes/${id}/review`,data), completeStocktake: (id) => client.post(`/stocktakes/${id}/complete`),
  qrcode: (code) => client.get(`/qrcodes/items/${encodeURIComponent(code)}`), exportItems: () => client.get('/excel/items/export', { responseType: 'blob' }), importItems: (file) => { const data = new FormData(); data.append('file',file); return client.post('/excel/items/import',data) },
  anomalies: () => client.get('/reports/anomalies'), ocrRecognize: (file) => { const data = new FormData(); data.append('file',file); return client.post('/ocr/recognize',data) },
}
